import tailwindcss from "@tailwindcss/vite";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import { VitePWA } from "vite-plugin-pwa";
import topLevelAwait from "vite-plugin-top-level-await";
import wasm from "vite-plugin-wasm";

export default defineConfig({
  plugins: [
    // Automerge ships its core as WASM (imported via the ESM-integration
    // proposal Vite/Rollup can't bundle natively). US-025 is the first screen to
    // mount the routine editor (Assemble → store → @automerge/automerge) in the
    // production bundle, so the web build now needs these plugins.
    wasm(),
    topLevelAwait(),
    react(),
    tailwindcss(),
    VitePWA({
      registerType: "autoUpdate",
      workbox: {
        // The Automerge core WASM (~3 MB) is part of the installable editor
        // shell, so allow it past Workbox's 2 MiB default precache cap.
        maximumFileSizeToCacheInBytes: 4 * 1024 * 1024,
      },
      manifest: {
        name: "Weave Steps",
        short_name: "Weave Steps",
        theme_color: "#2f5d8f",
        background_color: "#e9e6df",
        display: "standalone",
        // Generated by scripts/gen-pwa-icons.mjs (regenerate, don't hand-edit).
        // Real icons are what makes the manifest installable (US-050 AC-1).
        icons: [
          { src: "/pwa-192.png", sizes: "192x192", type: "image/png" },
          { src: "/pwa-512.png", sizes: "512x512", type: "image/png" },
          {
            src: "/pwa-512-maskable.png",
            sizes: "512x512",
            type: "image/png",
            purpose: "maskable",
          },
        ],
      },
    }),
  ],
  // Local dev: proxy API calls to `wrangler dev` (default port 8787).
  server: {
    proxy: {
      "/api": "http://localhost:8787",
    },
  },
});
