// GENERATED by scripts/gen-figure-charts (research bundle). Do not edit by hand.
// Real per-step both-role technique (WDSF-first, dancecentral.info primary), researched
// per figure. See docs/seed/figure-charts/ provenance. Regenerate to refresh.
import type { AuthoredStep } from "./figure-steps";

export const GENERATED_FIGURE_STEPS: Record<string, readonly AuthoredStep[]> = {
  "waltz:back-whisk": [
    {
      rise: "commence",
      position: "CBMP",
      leader: {
        direction: "back",
        footwork: "TH",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "forward",
        footwork: "HT",
        turn: "eighth_R",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "diagonal",
        footwork: "T",
        sway: "to_L",
      },
      follower: {
        direction: "side",
        footwork: "T",
        sway: "to_R",
        turn: "eighth_R",
      },
    },
    {
      rise: "up",
      position: "promenade",
      leader: {
        direction: "behind",
        footwork: "TH",
        sway: "to_L",
      },
      follower: {
        direction: "behind",
        footwork: "TH",
        sway: "to_R",
      },
    },
  ],
  "waltz:backward-lock": [
    {
      rise: "commence",
      position: "CBMP",
      leader: {
        direction: "back",
        footwork: "TH",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "forward",
        footwork: "HT",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "back",
        footwork: "T",
      },
      follower: {
        direction: "diagonal",
        footwork: "T",
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "diagonal",
        footwork: "T",
      },
      follower: {
        direction: "behind",
        footwork: "T",
      },
    },
    {
      rise: "up",
      leader: {
        direction: "diagonal",
        footwork: "TH",
      },
      follower: {
        direction: "diagonal",
        footwork: "TH",
      },
    },
  ],
  "waltz:basic-weave": [
    {
      leader: {
        direction: "back",
        footwork: "TH",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "forward",
        footwork: "H",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "commence",
      leader: {
        direction: "forward",
        footwork: "HT",
        turn: "eighth_L",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "back",
        footwork: "T",
        turn: "quarter_L",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "up",
      leader: {
        direction: "side",
        footwork: "TH",
        turn: "eighth_L",
      },
      follower: {
        direction: "side",
        footwork: "TH",
      },
    },
    {
      rise: "commence",
      position: "CBMP",
      leader: {
        direction: "back",
        footwork: "TH",
      },
      follower: {
        direction: "forward",
        footwork: "HT",
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "back",
        footwork: "T",
        turn: "quarter_L",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "forward",
        footwork: "T",
        turn: "quarter_L",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "up",
      leader: {
        direction: "side",
        footwork: "TH",
      },
      follower: {
        direction: "side",
        footwork: "TH",
      },
    },
  ],
  "waltz:chasse-from-pp": [
    {
      rise: "commence",
      position: "promenade",
      leader: {
        direction: "forward",
        footwork: "HT",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "forward",
        footwork: "HT",
        turn: "eighth_L",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "side",
        footwork: "T",
      },
      follower: {
        direction: "side",
        footwork: "T",
        turn: "eighth_L",
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "close",
        footwork: "T",
      },
      follower: {
        direction: "close",
        footwork: "T",
      },
    },
    {
      rise: "up",
      position: "closed",
      leader: {
        direction: "side",
        footwork: "TH",
      },
      follower: {
        direction: "side",
        footwork: "TH",
      },
    },
  ],
  "waltz:closed-change-on-lf": [
    {
      rise: "commence",
      leader: {
        direction: "forward",
        footwork: "HT",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "back",
        footwork: "TH",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "side",
        footwork: "T",
        sway: "to_L",
      },
      follower: {
        direction: "side",
        footwork: "T",
        sway: "to_R",
      },
    },
    {
      rise: "lowering",
      leader: {
        direction: "close",
        footwork: "TH",
        sway: "to_L",
      },
      follower: {
        direction: "close",
        footwork: "TH",
        sway: "to_R",
      },
    },
  ],
  "waltz:closed-change-on-rf": [
    {
      rise: "commence",
      leader: {
        direction: "forward",
        footwork: "HT",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "back",
        footwork: "TH",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "side",
        footwork: "T",
        sway: "to_R",
      },
      follower: {
        direction: "side",
        footwork: "T",
        sway: "to_L",
      },
    },
    {
      rise: "lowering",
      leader: {
        direction: "close",
        footwork: "TH",
        sway: "to_R",
      },
      follower: {
        direction: "close",
        footwork: "TH",
        sway: "to_L",
      },
    },
  ],
  "waltz:cross-hesitation-from-pp": [
    {
      rise: "commence",
      position: "promenade",
      leader: {
        direction: "forward",
        footwork: "HT",
      },
      follower: {
        direction: "forward",
        footwork: "HT",
        turn: "quarter_L",
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "close",
        footwork: "T",
      },
      follower: {
        direction: "side",
        footwork: "T",
        sway: "to_L",
        turn: "eighth_L",
      },
    },
    {
      rise: "lowering",
      leader: {
        direction: "in_place",
        footwork: "TH",
      },
      follower: {
        direction: "close",
        footwork: "TH",
        sway: "to_L",
      },
    },
  ],
  "waltz:double-reverse-spin": [
    {
      rise: "commence",
      leader: {
        direction: "forward",
        footwork: "HT",
        turn: "three_eighth_L",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "back",
        footwork: "TH",
        turn: "half_L",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "up",
      leader: {
        direction: "side",
        footwork: "T",
        turn: "half_L",
      },
      follower: {
        direction: "close",
        footwork: "HT",
        turn: "quarter_L",
      },
    },
    {
      rise: "lowering",
      leader: {
        direction: "close",
        footwork: "T",
      },
      follower: {
        direction: "forward",
        footwork: "TH",
        turn: "quarter_L",
      },
    },
  ],
  "waltz:drag-hesitation": [
    {
      leader: {
        direction: "forward",
        footwork: "HT",
        turn: "quarter_L",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "back",
        footwork: "TH",
        turn: "quarter_L",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "commence",
      leader: {
        direction: "side",
        footwork: "T",
        turn: "eighth_L",
      },
      follower: {
        direction: "side",
        footwork: "T",
        turn: "eighth_L",
      },
    },
    {
      rise: "up",
      leader: {
        direction: "close",
        footwork: "T/TH",
      },
      follower: {
        direction: "close",
        footwork: "T/TH",
      },
    },
  ],
  "waltz:fallaway-reverse-and-slip-pivot": [
    {
      rise: "commence",
      leader: {
        direction: "forward",
        footwork: "HT",
        turn: "quarter_L",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "back",
        footwork: "TH",
      },
    },
    {
      rise: "up",
      leader: {
        direction: "back",
        footwork: "T",
        turn: "eighth_L",
      },
      follower: {
        direction: "back",
        footwork: "T",
      },
    },
    {
      rise: "up",
      position: "CBMP",
      leader: {
        direction: "back",
        footwork: "TH",
        turn: "quarter_L",
      },
      follower: {
        direction: "back",
        footwork: "T",
        turn: "half_L",
        bodyActions: ["CBM"],
      },
    },
    {
      position: "CBMP",
      leader: {
        direction: "back",
        footwork: "T/TH",
        turn: "quarter_L",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "forward",
        footwork: "TH",
        turn: "quarter_L",
        bodyActions: ["CBM"],
      },
    },
  ],
  "waltz:hesitation-change": [
    {
      leader: {
        direction: "back",
        footwork: "H",
        turn: "three_eighth_R",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "forward",
        footwork: "HT",
        turn: "three_eighth_R",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "NFR",
      leader: {
        direction: "side",
        footwork: "heel pull",
        sway: "to_L",
      },
      follower: {
        direction: "side",
        footwork: "TH",
        sway: "to_R",
      },
    },
    {
      rise: "body_rise",
      leader: {
        direction: "close",
        footwork: "T",
        sway: "to_L",
      },
      follower: {
        direction: "close",
        footwork: "T",
        sway: "to_R",
      },
    },
  ],
  "waltz:hover-corte": [
    {
      rise: "commence",
      position: "closed",
      leader: {
        direction: "back",
        footwork: "TH",
        turn: "three_eighth_L",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "forward",
        footwork: "HT",
        turn: "quarter_L",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "side",
        footwork: "T",
        sway: "to_R",
      },
      follower: {
        direction: "side",
        footwork: "T",
        sway: "to_L",
      },
    },
    {
      rise: "lowering",
      leader: {
        direction: "back",
        footwork: "TH",
      },
      follower: {
        direction: "diagonal",
        footwork: "TH",
      },
    },
  ],
  "waltz:impetus": [
    {
      leader: {
        direction: "back",
        footwork: "TH",
        turn: "three_eighth_R",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "forward",
        footwork: "HT",
        turn: "three_eighth_R",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "commence",
      leader: {
        direction: "close",
        footwork: "H",
        sway: "to_L",
        turn: "quarter_R",
      },
      follower: {
        direction: "side",
        footwork: "T",
        sway: "to_R",
        turn: "quarter_R",
      },
    },
    {
      rise: "lowering",
      leader: {
        direction: "side",
        footwork: "TH",
      },
      follower: {
        direction: "diagonal",
        footwork: "TH",
      },
    },
  ],
  "waltz:impetus-to-pp": [
    {
      leader: {
        direction: "back",
        footwork: "TH",
        turn: "three_eighth_R",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "forward",
        footwork: "HT",
        turn: "three_eighth_R",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "commence",
      leader: {
        direction: "close",
        footwork: "H",
        sway: "to_L",
      },
      follower: {
        direction: "side",
        footwork: "T",
        sway: "to_R",
        turn: "three_eighth_R",
      },
    },
    {
      rise: "lowering",
      position: "promenade",
      leader: {
        direction: "diagonal",
        footwork: "TH",
      },
      follower: {
        direction: "side",
        footwork: "TH",
      },
    },
  ],
  "waltz:natural-spin-turn": [
    {
      rise: "commence",
      position: "closed",
      leader: {
        direction: "forward",
        footwork: "HT",
        turn: "quarter_R",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "back",
        footwork: "TH",
        turn: "three_eighth_R",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "side",
        footwork: "T",
        sway: "to_R",
        turn: "eighth_R",
      },
      follower: {
        direction: "side",
        footwork: "T",
        sway: "to_L",
      },
    },
    {
      rise: "lowering",
      leader: {
        direction: "close",
        footwork: "TH",
      },
      follower: {
        direction: "close",
        footwork: "TH",
      },
    },
    {
      position: "CBMP",
      leader: {
        direction: "back",
        footwork: "T/H/T",
        turn: "half_R",
      },
      follower: {
        direction: "forward",
        footwork: "HT",
        turn: "half_R",
      },
    },
    {
      rise: "commence",
      position: "CBMP",
      leader: {
        direction: "forward",
        footwork: "HT",
        turn: "three_eighth_R",
      },
      follower: {
        direction: "back",
        footwork: "T",
        turn: "three_eighth_R",
      },
    },
    {
      rise: "lowering",
      leader: {
        direction: "side",
        footwork: "TH",
      },
      follower: {
        direction: "diagonal",
        footwork: "TH",
      },
    },
  ],
  "waltz:natural-turn": [
    {
      rise: "commence",
      position: "closed",
      leader: {
        direction: "forward",
        footwork: "HT",
        turn: "quarter_R",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "back",
        footwork: "TH",
        turn: "three_eighth_R",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "side",
        footwork: "T",
        sway: "to_R",
        turn: "eighth_R",
      },
      follower: {
        direction: "side",
        footwork: "T",
        sway: "to_L",
      },
    },
    {
      rise: "lowering",
      leader: {
        direction: "close",
        footwork: "TH",
        sway: "to_R",
      },
      follower: {
        direction: "close",
        footwork: "TH",
        sway: "to_L",
      },
    },
    {
      rise: "commence",
      leader: {
        direction: "back",
        footwork: "TH",
        turn: "three_eighth_R",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "forward",
        footwork: "HT",
        turn: "quarter_R",
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "side",
        footwork: "T",
        sway: "to_L",
      },
      follower: {
        direction: "side",
        footwork: "T",
        sway: "to_R",
        turn: "eighth_R",
      },
    },
    {
      rise: "lowering",
      leader: {
        direction: "close",
        footwork: "TH",
        sway: "to_L",
      },
      follower: {
        direction: "close",
        footwork: "TH",
      },
    },
  ],
  "waltz:natural-turning-lock": [
    {
      rise: "commence",
      leader: {
        direction: "back",
        footwork: "T",
        turn: "quarter_R",
      },
      follower: {
        direction: "forward",
        footwork: "T",
        turn: "quarter_R",
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "forward",
        footwork: "T",
      },
      follower: {
        direction: "behind",
        footwork: "T",
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "side",
        footwork: "T",
        turn: "eighth_R",
      },
      follower: {
        direction: "side",
        footwork: "T",
        turn: "eighth_R",
      },
    },
    {
      rise: "lowering",
      position: "promenade",
      leader: {
        direction: "diagonal",
        footwork: "TH",
      },
      follower: {
        direction: "side",
        footwork: "TH",
        turn: "three_eighth_R",
      },
    },
  ],
  "waltz:outside-change": [
    {
      rise: "commence",
      position: "CBMP",
      leader: {
        direction: "back",
        footwork: "TH",
      },
      follower: {
        direction: "forward",
        footwork: "HT",
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "back",
        footwork: "T",
        turn: "quarter_L",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "forward",
        footwork: "T",
        turn: "quarter_L",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "lowering",
      position: "closed",
      leader: {
        direction: "side",
        footwork: "TH",
      },
      follower: {
        direction: "side",
        footwork: "TH",
      },
    },
  ],
  "waltz:outside-spin": [
    {
      rise: "commence",
      position: "CBMP",
      leader: {
        direction: "back",
        footwork: "T/H/T",
        turn: "three_eighth_R",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "forward",
        footwork: "HT",
        turn: "half_R",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "continue",
      position: "CBMP",
      leader: {
        direction: "forward",
        footwork: "HT",
        turn: "three_eighth_R",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "close",
        footwork: "T",
        turn: "quarter_R",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "lowering",
      leader: {
        direction: "side",
        footwork: "TH",
        turn: "quarter_R",
      },
      follower: {
        direction: "forward",
        footwork: "TH",
        turn: "eighth_R",
      },
    },
  ],
  "waltz:progressive-chasse-to-r": [
    {
      rise: "commence",
      leader: {
        direction: "forward",
        footwork: "HT",
        turn: "eighth_L",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "back",
        footwork: "TH",
        turn: "quarter_L",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "side",
        footwork: "T",
        turn: "eighth_L",
      },
      follower: {
        direction: "side",
        footwork: "T",
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "close",
        footwork: "T",
      },
      follower: {
        direction: "close",
        footwork: "T",
      },
    },
    {
      rise: "lowering",
      leader: {
        direction: "side",
        footwork: "TH",
      },
      follower: {
        direction: "side",
        footwork: "TH",
      },
    },
  ],
  "waltz:quick-open-reverse": [
    {
      rise: "commence",
      leader: {
        direction: "forward",
        footwork: "HT",
        turn: "three_eighth_L",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "back",
        footwork: "TH",
        turn: "half_L",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "up",
      leader: {
        direction: "side",
        footwork: "T",
        sway: "to_L",
      },
      follower: {
        direction: "side",
        footwork: "T",
        sway: "to_R",
      },
    },
    {
      rise: "lowering",
      position: "CBMP",
      leader: {
        direction: "back",
        footwork: "TH",
        sway: "to_L",
        turn: "eighth_L",
      },
      follower: {
        direction: "forward",
        footwork: "TH",
        sway: "to_R",
      },
    },
    {
      leader: {
        direction: "back",
        footwork: "T",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "forward",
        footwork: "H",
        bodyActions: ["CBM"],
      },
    },
  ],
  "waltz:reverse-pivot": [
    {
      position: "CBMP",
      leader: {
        direction: "back",
        footwork: "TH",
        turn: "half_L",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "forward",
        footwork: "HT",
        turn: "half_L",
        bodyActions: ["CBM"],
      },
    },
  ],
  "waltz:reverse-turn": [
    {
      rise: "commence",
      leader: {
        direction: "forward",
        footwork: "HT",
        turn: "quarter_L",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "back",
        footwork: "TH",
        turn: "three_eighth_L",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "side",
        footwork: "T",
        sway: "to_L",
        turn: "eighth_L",
      },
      follower: {
        direction: "side",
        footwork: "T",
        sway: "to_R",
      },
    },
    {
      rise: "lowering",
      leader: {
        direction: "close",
        footwork: "TH",
        sway: "to_L",
      },
      follower: {
        direction: "close",
        footwork: "TH",
        sway: "to_R",
      },
    },
    {
      rise: "commence",
      leader: {
        direction: "back",
        footwork: "TH",
        turn: "three_eighth_L",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "forward",
        footwork: "HT",
        turn: "quarter_L",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "side",
        footwork: "T",
        sway: "to_R",
      },
      follower: {
        direction: "side",
        footwork: "T",
        sway: "to_L",
        turn: "eighth_L",
      },
    },
    {
      rise: "lowering",
      leader: {
        direction: "close",
        footwork: "TH",
        sway: "to_R",
      },
      follower: {
        direction: "close",
        footwork: "TH",
        sway: "to_L",
      },
    },
  ],
  "waltz:reverse-turning-lock": [
    {
      rise: "commence",
      leader: {
        direction: "back",
        footwork: "T",
        sway: "to_L",
      },
      follower: {
        direction: "forward",
        footwork: "T",
        sway: "to_R",
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "back",
        footwork: "T",
        sway: "to_L",
      },
      follower: {
        direction: "behind",
        footwork: "T",
        sway: "to_R",
      },
    },
    {
      rise: "up",
      leader: {
        direction: "back",
        footwork: "T",
        turn: "eighth_L",
      },
      follower: {
        direction: "forward",
        footwork: "T",
        turn: "eighth_L",
      },
    },
    {
      rise: "up",
      leader: {
        direction: "side",
        footwork: "TH",
        turn: "quarter_L",
      },
      follower: {
        direction: "side",
        footwork: "TH",
        turn: "quarter_L",
      },
    },
  ],
  "waltz:telemark": [
    {
      rise: "commence",
      leader: {
        direction: "forward",
        footwork: "HT",
        turn: "three_eighth_L",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "back",
        footwork: "TH",
        turn: "three_eighth_L",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "up",
      leader: {
        direction: "side",
        footwork: "T",
        sway: "to_L",
        turn: "three_eighth_L",
      },
      follower: {
        direction: "close",
        footwork: "H",
        sway: "to_R",
        turn: "three_eighth_L",
      },
    },
    {
      rise: "lowering",
      leader: {
        direction: "side",
        footwork: "TH",
      },
      follower: {
        direction: "side",
        footwork: "TH",
      },
    },
  ],
  "waltz:telemark-to-pp": [
    {
      rise: "commence",
      leader: {
        direction: "forward",
        footwork: "HT",
        turn: "quarter_L",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "back",
        footwork: "TH",
        turn: "three_eighth_L",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "up",
      leader: {
        direction: "side",
        footwork: "T",
        sway: "to_L",
        turn: "half_L",
      },
      follower: {
        direction: "close",
        footwork: "H",
        sway: "to_R",
      },
    },
    {
      rise: "lowering",
      position: "promenade",
      leader: {
        direction: "side",
        footwork: "TH",
      },
      follower: {
        direction: "forward",
        footwork: "TH",
      },
    },
  ],
  "waltz:weave-from-pp": [
    {
      rise: "commence",
      position: "CBMP",
      leader: {
        direction: "forward",
        footwork: "HT",
        turn: "eighth_L",
      },
      follower: {
        direction: "forward",
        footwork: "HT",
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "forward",
        footwork: "T",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "side",
        footwork: "T",
        turn: "three_eighth_L",
      },
    },
    {
      rise: "lowering",
      leader: {
        direction: "side",
        footwork: "TH",
        turn: "quarter_L",
      },
      follower: {
        direction: "side",
        footwork: "TH",
        turn: "half_L",
      },
    },
    {
      rise: "commence",
      position: "CBMP",
      leader: {
        direction: "back",
        footwork: "TH",
        turn: "eighth_L",
      },
      follower: {
        direction: "forward",
        footwork: "HT",
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "back",
        footwork: "T",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "forward",
        footwork: "T",
        bodyActions: ["CBM"],
      },
    },
    {
      rise: "lowering",
      leader: {
        direction: "side",
        footwork: "TH",
        turn: "quarter_L",
      },
      follower: {
        direction: "side",
        footwork: "TH",
        turn: "quarter_L",
      },
    },
  ],
  "waltz:whisk": [
    {
      rise: "commence",
      leader: {
        direction: "forward",
        footwork: "HT",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "back",
        footwork: "TH",
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "side",
        footwork: "T",
        sway: "to_L",
      },
      follower: {
        direction: "diagonal",
        footwork: "T",
        sway: "to_R",
        turn: "quarter_R",
      },
    },
    {
      rise: "lowering",
      position: "promenade",
      leader: {
        direction: "behind",
        footwork: "TH",
        sway: "to_L",
      },
      follower: {
        direction: "behind",
        footwork: "TH",
        sway: "to_R",
      },
    },
  ],
  "waltz:wing": [
    {
      rise: "commence",
      position: "CBMP",
      leader: {
        direction: "forward",
        footwork: "H",
        turn: "eighth_L",
      },
      follower: {
        direction: "forward",
        footwork: "HT",
        turn: "eighth_L",
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "close",
        footwork: "T",
      },
      follower: {
        direction: "forward",
        footwork: "T",
        sway: "to_L",
        turn: "eighth_L",
      },
    },
    {
      rise: "lowering",
      position: "wing",
      leader: {
        direction: "close",
        footwork: "T",
        turn: "eighth_L",
      },
      follower: {
        direction: "forward",
        footwork: "TH",
        sway: "to_L",
        turn: "quarter_L",
      },
    },
  ],
  "waltz:wing-from-pp": [
    {
      rise: "commence",
      position: "promenade",
      leader: {
        direction: "forward",
        footwork: "H",
        turn: "eighth_L",
        bodyActions: ["CBM"],
      },
      follower: {
        direction: "forward",
        footwork: "HT",
        turn: "eighth_L",
      },
    },
    {
      rise: "continue",
      leader: {
        direction: "close",
        footwork: "T",
      },
      follower: {
        direction: "forward",
        footwork: "T",
        sway: "to_L",
        turn: "eighth_L",
      },
    },
    {
      rise: "lowering",
      position: "wing",
      leader: {
        direction: "close",
        footwork: "T",
        turn: "eighth_L",
      },
      follower: {
        direction: "forward",
        footwork: "TH",
        sway: "to_L",
        turn: "quarter_L",
      },
    },
  ],
};
