// US-032 — the application-global figure library. A client-bundled catalog (PLAN
// §4.2 / D30 "reference data ships in the bundle") shaped from the ISTD Standard
// syllabus seed (see library-data.ts, regenerated by scripts/gen-library.mjs).
//
// v1 carries identity fields + WDSF timing attributes where available.
// ISTD figures with matching WDSF syllabus entries carry parsed step attributes;
// net-new WDSF figures also carry attributes; ISTD-only figures carry identity only.
// Picking a preset seeds an owned figure with this canonical name + figureType —
// the cross-routine identity that later enables figure-level features;
// notation is then entered on the timeline (US-028).
import type { DanceId } from "./dances";
import type { Attribute } from "./doc-types";
import { LIBRARY_FIGURE_DATA } from "./library-data";
import { buildWdsfAttributes } from "./wdsf-timing";

/** One catalog figure: identity + (for WDSF-enriched figures) its parsed step timeline. */
export interface LibraryFigure {
  dance: DanceId;
  figureType: string;
  name: string;
  /** Raw WDSF timing string (provenance/display); absent for ISTD-only figures. */
  timing?: string;
  /** WDSF syllabus notes, if any. */
  notes?: string[];
  /** Per-step timeline parsed from the WDSF timing + start/finish actions. */
  attributes?: Attribute[];
}

/** A figureType family within one dance (for the grouped library browse). */
export interface LibraryGroup {
  figureType: string;
  figures: LibraryFigure[];
}

/** The whole catalog. WDSF-enriched figures carry a parsed `attributes` timeline. */
export const LIBRARY_FIGURES: readonly LibraryFigure[] = LIBRARY_FIGURE_DATA.map((d) => {
  if (!d.timing) return { dance: d.dance, figureType: d.figureType, name: d.name };
  return {
    dance: d.dance,
    figureType: d.figureType,
    name: d.name,
    timing: d.timing,
    notes: d.notes,
    attributes: buildWdsfAttributes({
      figureType: d.figureType,
      dance: d.dance,
      timing: d.timing,
      start: d.start,
      finish: d.finish,
    }),
  };
});

/** The catalog figures for one dance (the picker is always dance-scoped). */
export function libraryFiguresForDance(dance: DanceId): LibraryFigure[] {
  return LIBRARY_FIGURES.filter((f) => f.dance === dance);
}

/**
 * One dance's figures grouped by figureType, preserving first-seen order — the
 * shape the Library browse renders (a heading per family). Most families hold a
 * single figure today; the grouping keeps room for per-dance variations.
 */
export function libraryGroupsForDance(dance: DanceId): LibraryGroup[] {
  const groups = new Map<string, LibraryGroup>();
  for (const figure of libraryFiguresForDance(dance)) {
    const group = groups.get(figure.figureType);
    if (group) group.figures.push(figure);
    else groups.set(figure.figureType, { figureType: figure.figureType, figures: [figure] });
  }
  return [...groups.values()];
}
