// US-032 — the application-global figure library. A client-bundled catalog (PLAN
// §4.2 / D30 "reference data ships in the bundle") shaped from the ISTD Standard
// syllabus seed (see library-data.ts, regenerated by scripts/gen-library.mjs).
//
// v1 carries only the identity fields a user needs to PICK a figure (dance,
// figureType, name); per-count attribute timelines are the content workstream
// (the seed ships them empty). Picking a preset seeds an owned figure with this
// canonical name + figureType — the cross-routine identity that later enables
// figure-level features; notation is then entered on the timeline (US-028).
import type { DanceId } from "./dances";
import { LIBRARY_FIGURE_DATA } from "./library-data";

/** One catalog figure: its dance, canonical figureType (identity), and name. */
export interface LibraryFigure {
  dance: DanceId;
  figureType: string;
  name: string;
}

/** A figureType family within one dance (for the grouped library browse). */
export interface LibraryGroup {
  figureType: string;
  figures: LibraryFigure[];
}

/** The whole catalog. */
export const LIBRARY_FIGURES: readonly LibraryFigure[] = LIBRARY_FIGURE_DATA;

/** The catalog figures for one dance (the picker is always dance-scoped). */
export function libraryFiguresForDance(dance: DanceId): LibraryFigure[] {
  return LIBRARY_FIGURES.filter((f) => f.dance === dance);
}

/**
 * One dance's figures grouped by figureType, preserving first-seen order — the
 * shape the Library browse renders (a heading per family). Most families hold a
 * single figure today; the grouping keeps room for per-dance variations.
 */
export function libraryGroupsForDance(dance: DanceId): LibraryGroup[] {
  const groups = new Map<string, LibraryGroup>();
  for (const figure of libraryFiguresForDance(dance)) {
    const group = groups.get(figure.figureType);
    if (group) group.figures.push(figure);
    else groups.set(figure.figureType, { figureType: figure.figureType, figures: [figure] });
  }
  return [...groups.values()];
}
