// GENERATED from docs/seed/istd-standard-figures.json — do not edit by hand.
// Regenerate with scripts/gen-library.mjs. Source: ISTD International Standard
// (Modern Ballroom) syllabus figure list — shaped into the client-bundled figure
// catalog (PLAN reference-data decision; per-count attributes are filled later).
import type { DanceId } from "./dances";

export interface LibraryFigureData {
  dance: DanceId;
  figureType: string;
  name: string;
}

/** 122 canonical figures across the five Standard dances. */
export const LIBRARY_FIGURE_DATA: readonly LibraryFigureData[] = [
  { dance: "waltz", figureType: "back-lock", name: "Back Lock" },
  { dance: "waltz", figureType: "back-whisk", name: "Back Whisk" },
  { dance: "waltz", figureType: "basic-weave", name: "Basic Weave" },
  { dance: "waltz", figureType: "chasse-from-pp", name: "Chassé from PP" },
  { dance: "waltz", figureType: "closed-changes", name: "Closed Changes" },
  { dance: "waltz", figureType: "closed-impetus", name: "Closed Impetus" },
  { dance: "waltz", figureType: "closed-telemark", name: "Closed Telemark" },
  { dance: "waltz", figureType: "closed-wing", name: "Closed Wing" },
  { dance: "waltz", figureType: "contra-check", name: "Contra Check" },
  { dance: "waltz", figureType: "double-reverse-spin", name: "Double Reverse Spin" },
  { dance: "waltz", figureType: "drag-hesitation", name: "Drag Hesitation" },
  {
    dance: "waltz",
    figureType: "fallaway-reverse-and-slip-pivot",
    name: "Fallaway Reverse and Slip Pivot",
  },
  { dance: "waltz", figureType: "fallaway-whisk", name: "Fallaway Whisk" },
  { dance: "waltz", figureType: "hesitation-change", name: "Hesitation Change" },
  { dance: "waltz", figureType: "hover-corte", name: "Hover Corté" },
  { dance: "waltz", figureType: "left-whisk", name: "Left Whisk" },
  { dance: "waltz", figureType: "natural-spin-turn", name: "Natural Spin Turn" },
  { dance: "waltz", figureType: "natural-turn", name: "Natural Turn" },
  {
    dance: "waltz",
    figureType: "open-impetus-and-cross-hesitation",
    name: "Open Impetus and Cross Hesitation",
  },
  { dance: "waltz", figureType: "open-impetus-and-wing", name: "Open Impetus and Wing" },
  {
    dance: "waltz",
    figureType: "open-telemark-and-cross-hesitation",
    name: "Open Telemark and Cross Hesitation",
  },
  { dance: "waltz", figureType: "open-telemark-and-wing", name: "Open Telemark and Wing" },
  { dance: "waltz", figureType: "outside-change", name: "Outside Change" },
  { dance: "waltz", figureType: "outside-spin", name: "Outside Spin" },
  { dance: "waltz", figureType: "progressive-chasse-to-r", name: "Progressive Chassé to R" },
  { dance: "waltz", figureType: "reverse-corte", name: "Reverse Corté" },
  { dance: "waltz", figureType: "reverse-pivot", name: "Reverse Pivot" },
  { dance: "waltz", figureType: "reverse-turn", name: "Reverse Turn" },
  { dance: "waltz", figureType: "turning-lock", name: "Turning Lock" },
  { dance: "waltz", figureType: "turning-lock-to-r", name: "Turning Lock to R" },
  { dance: "waltz", figureType: "weave-from-pp", name: "Weave from PP" },
  { dance: "waltz", figureType: "whisk", name: "Whisk" },
  { dance: "viennese_waltz", figureType: "backward-change-step", name: "Backward Change Step" },
  { dance: "viennese_waltz", figureType: "contra-check", name: "Contra Check" },
  { dance: "viennese_waltz", figureType: "forward-change-step", name: "Forward Change Step" },
  { dance: "viennese_waltz", figureType: "natural-fleckerl", name: "Natural Fleckerl" },
  { dance: "viennese_waltz", figureType: "natural-turn", name: "Natural Turn" },
  { dance: "viennese_waltz", figureType: "reverse-fleckerl", name: "Reverse Fleckerl" },
  { dance: "viennese_waltz", figureType: "reverse-turn", name: "Reverse Turn" },
  { dance: "quickstep", figureType: "backward-lock", name: "Backward Lock" },
  { dance: "quickstep", figureType: "change-of-direction", name: "Change of Direction" },
  { dance: "quickstep", figureType: "chasse-reverse-turn", name: "Chassé Reverse Turn" },
  { dance: "quickstep", figureType: "closed-impetus", name: "Closed Impetus" },
  { dance: "quickstep", figureType: "closed-telemark", name: "Closed Telemark" },
  { dance: "quickstep", figureType: "cross-chasse", name: "Cross Chassé" },
  { dance: "quickstep", figureType: "cross-swivel", name: "Cross Swivel" },
  { dance: "quickstep", figureType: "double-reverse-spin", name: "Double Reverse Spin" },
  { dance: "quickstep", figureType: "fishtail", name: "Fishtail" },
  { dance: "quickstep", figureType: "forward-lock", name: "Forward Lock" },
  { dance: "quickstep", figureType: "four-quick-run", name: "Four Quick Run" },
  { dance: "quickstep", figureType: "heel-pivot", name: "Heel Pivot (Quarter Turn to Left)" },
  { dance: "quickstep", figureType: "hover-corte", name: "Hover Corté" },
  { dance: "quickstep", figureType: "natural-pivot-turn", name: "Natural Pivot Turn" },
  { dance: "quickstep", figureType: "natural-spin-turn", name: "Natural Spin Turn" },
  { dance: "quickstep", figureType: "natural-turn", name: "Natural Turn" },
  {
    dance: "quickstep",
    figureType: "natural-turn-and-back-lock",
    name: "Natural Turn and Back Lock",
  },
  {
    dance: "quickstep",
    figureType: "natural-turn-with-hesitation",
    name: "Natural Turn with Hesitation",
  },
  { dance: "quickstep", figureType: "progressive-chasse", name: "Progressive Chassé" },
  { dance: "quickstep", figureType: "progressive-chasse-to-r", name: "Progressive Chassé to R" },
  { dance: "quickstep", figureType: "quarter-turn-to-r", name: "Quarter Turn to R" },
  { dance: "quickstep", figureType: "quick-open-reverse", name: "Quick Open Reverse" },
  { dance: "quickstep", figureType: "reverse-pivot", name: "Reverse Pivot" },
  { dance: "quickstep", figureType: "rumba-cross", name: "Rumba Cross" },
  { dance: "quickstep", figureType: "running-finish", name: "Running Finish" },
  { dance: "quickstep", figureType: "running-right-turn", name: "Running Right Turn" },
  { dance: "quickstep", figureType: "six-quick-run", name: "Six Quick Run" },
  { dance: "quickstep", figureType: "tipple-chasse-to-r", name: "Tipple Chassé to R" },
  { dance: "quickstep", figureType: "tipsy-to-r-or-l", name: "Tipsy to R or L" },
  { dance: "quickstep", figureType: "v6", name: "V6" },
  {
    dance: "quickstep",
    figureType: "zig-zag-back-lock-and-running-finish",
    name: "Zig Zag, Back Lock and Running Finish",
  },
  { dance: "foxtrot", figureType: "basic-weave", name: "Basic Weave" },
  {
    dance: "foxtrot",
    figureType: "bounce-fallaway-with-weave-ending",
    name: "Bounce Fallaway with Weave Ending",
  },
  { dance: "foxtrot", figureType: "change-of-direction", name: "Change of Direction" },
  {
    dance: "foxtrot",
    figureType: "closed-impetus-and-feather-finish",
    name: "Closed Impetus and Feather Finish",
  },
  { dance: "foxtrot", figureType: "closed-telemark", name: "Closed Telemark" },
  {
    dance: "foxtrot",
    figureType: "curved-feather-to-back-feather",
    name: "Curved Feather to Back Feather",
  },
  {
    dance: "foxtrot",
    figureType: "fallaway-reverse-and-slip-pivot",
    name: "Fallaway Reverse and Slip Pivot",
  },
  { dance: "foxtrot", figureType: "feather-step", name: "Feather Step" },
  { dance: "foxtrot", figureType: "hover-cross", name: "Hover Cross" },
  { dance: "foxtrot", figureType: "hover-feather", name: "Hover Feather" },
  { dance: "foxtrot", figureType: "hover-telemark", name: "Hover Telemark" },
  { dance: "foxtrot", figureType: "natural-hover-telemark", name: "Natural Hover Telemark" },
  { dance: "foxtrot", figureType: "natural-telemark", name: "Natural Telemark" },
  { dance: "foxtrot", figureType: "natural-turn", name: "Natural Turn" },
  { dance: "foxtrot", figureType: "natural-twist-turn", name: "Natural Twist Turn" },
  { dance: "foxtrot", figureType: "natural-weave", name: "Natural Weave" },
  { dance: "foxtrot", figureType: "natural-zig-zag-from-pp", name: "Natural Zig-Zag from PP" },
  { dance: "foxtrot", figureType: "open-impetus", name: "Open Impetus" },
  {
    dance: "foxtrot",
    figureType: "open-telemark-and-feather-ending",
    name: "Open Telemark and Feather Ending",
  },
  {
    dance: "foxtrot",
    figureType: "open-telemark-natural-turn-outside-swivel-feather-ending",
    name: "Open Telemark, Natural Turn, Outside Swivel, Feather Ending",
  },
  {
    dance: "foxtrot",
    figureType: "reverse-turn",
    name: "Reverse Turn (incorporating Feather Finish)",
  },
  { dance: "foxtrot", figureType: "reverse-wave", name: "Reverse Wave" },
  { dance: "foxtrot", figureType: "three-step", name: "Three Step" },
  { dance: "foxtrot", figureType: "top-spin", name: "Top Spin" },
  { dance: "foxtrot", figureType: "weave-from-pp", name: "Weave from PP" },
  { dance: "tango", figureType: "back-corte", name: "Back Corté" },
  { dance: "tango", figureType: "back-open-promenade", name: "Back Open Promenade" },
  { dance: "tango", figureType: "basic-reverse-turn", name: "Basic Reverse Turn" },
  { dance: "tango", figureType: "brush-tap", name: "Brush Tap" },
  { dance: "tango", figureType: "closed-promenade", name: "Closed Promenade" },
  { dance: "tango", figureType: "contra-check", name: "Contra Check" },
  { dance: "tango", figureType: "fallaway-four-step", name: "Fallaway Four Step" },
  { dance: "tango", figureType: "fallaway-promenade", name: "Fallaway Promenade" },
  {
    dance: "tango",
    figureType: "fallaway-reverse-and-slip-pivot",
    name: "Fallaway Reverse and Slip Pivot",
  },
  { dance: "tango", figureType: "five-step", name: "Five Step" },
  { dance: "tango", figureType: "four-step", name: "Four Step" },
  { dance: "tango", figureType: "four-step-change", name: "Four Step Change" },
  { dance: "tango", figureType: "lf-and-rf-rocks", name: "LF and RF Rocks" },
  { dance: "tango", figureType: "natural-promenade-turn", name: "Natural Promenade Turn" },
  { dance: "tango", figureType: "natural-twist-turn", name: "Natural Twist Turn" },
  { dance: "tango", figureType: "open-promenade", name: "Open Promenade" },
  {
    dance: "tango",
    figureType: "open-reverse-turn-partner-in-line",
    name: "Open Reverse Turn, Partner in Line",
  },
  {
    dance: "tango",
    figureType: "open-reverse-turn-partner-outside",
    name: "Open Reverse Turn, Partner Outside",
  },
  { dance: "tango", figureType: "outside-swivels", name: "Outside Swivels" },
  { dance: "tango", figureType: "oversway", name: "Oversway" },
  { dance: "tango", figureType: "progressive-link", name: "Progressive Link" },
  { dance: "tango", figureType: "progressive-side-step", name: "Progressive Side Step" },
  {
    dance: "tango",
    figureType: "progressive-side-step-reverse-turn",
    name: "Progressive Side Step Reverse Turn",
  },
  { dance: "tango", figureType: "promenade-link", name: "Promenade Link" },
  { dance: "tango", figureType: "rock-turn", name: "Rock Turn" },
  { dance: "tango", figureType: "the-chase", name: "The Chase" },
  { dance: "tango", figureType: "walk", name: "Walk" },
];
