// US-032 — the application-global figure library. A client-bundled catalog (PLAN
// §4.2 / D30 "reference data ships in the bundle") shaped from the ISTD Standard
// syllabus seed (see library-data.ts, regenerated by scripts/gen-library.mjs).
//
// v1 carries identity fields + WDSF timing attributes where available.
// ISTD figures with matching WDSF syllabus entries carry parsed step attributes;
// net-new WDSF figures also carry attributes; ISTD-only figures carry identity only.
// Picking a preset seeds an owned figure with this canonical name + figureType —
// the cross-routine identity that later enables figure-level features;
// notation is then entered on the timeline (US-028).
import { type DanceId, isDanceId } from "./dances";
import type { Alignment, Attribute } from "./doc-types";
import { authoredAlignment } from "./figure-steps";
import { LIBRARY_FIGURE_DATA } from "./library-data";
import { buildWdsfAttributes } from "./wdsf-timing";

/** One catalog figure: identity + (for WDSF-enriched figures) its parsed step timeline. */
export interface LibraryFigure {
  dance: DanceId;
  figureType: string;
  name: string;
  /** Raw WDSF timing string (provenance/display); absent for ISTD-only figures. */
  timing?: string;
  /** WDSF syllabus notes, if any. */
  notes?: string[];
  /** Per-step timeline parsed from the WDSF timing + start/finish actions. */
  attributes?: Attribute[];
  /** Figure-level entry alignment (per-figure, leader's perspective), where charted. */
  entryAlignment?: Alignment;
  /** Figure-level exit alignment (per-figure, leader's perspective), where charted. */
  exitAlignment?: Alignment;
}

/** A figureType family within one dance (for the grouped library browse). */
export interface LibraryGroup {
  figureType: string;
  figures: LibraryFigure[];
}

/** The whole catalog. WDSF-enriched figures carry a parsed `attributes` timeline. */
export const LIBRARY_FIGURES: readonly LibraryFigure[] = LIBRARY_FIGURE_DATA.map((d) => {
  const align = authoredAlignment(d.dance, d.figureType);
  if (!d.timing) {
    return {
      dance: d.dance,
      figureType: d.figureType,
      name: d.name,
      ...(align?.entry && { entryAlignment: align.entry }),
      ...(align?.exit && { exitAlignment: align.exit }),
    };
  }
  return {
    dance: d.dance,
    figureType: d.figureType,
    name: d.name,
    timing: d.timing,
    notes: d.notes,
    attributes: buildWdsfAttributes({
      figureType: d.figureType,
      dance: d.dance,
      timing: d.timing,
      start: d.start,
      finish: d.finish,
    }),
    ...(align?.entry && { entryAlignment: align.entry }),
    ...(align?.exit && { exitAlignment: align.exit }),
  };
});

/** The catalog figures for one dance (the picker is always dance-scoped). */
export function libraryFiguresForDance(dance: DanceId): LibraryFigure[] {
  return LIBRARY_FIGURES.filter((f) => f.dance === dance);
}

/**
 * One dance's figures grouped by figureType, preserving first-seen order — the
 * shape the Library browse renders (a heading per family). Most families hold a
 * single figure today; the grouping keeps room for per-dance variations.
 */
export function libraryGroupsForDance(dance: DanceId): LibraryGroup[] {
  const groups = new Map<string, LibraryGroup>();
  for (const figure of libraryFiguresForDance(dance)) {
    const group = groups.get(figure.figureType);
    if (group) group.figures.push(figure);
    else groups.set(figure.figureType, { figureType: figure.figureType, figures: [figure] });
  }
  return [...groups.values()];
}

/**
 * The canonical provenance ref for a global-catalog figure (T5 / PLAN §5.2). A
 * bundled catalog figure has no Automerge URL of its own (it's reference data, not
 * a DO), so the cross-dance identity `(dance × figureType)` is its stable id.
 * ⟳v5: this is now also a directly BOOKMARKABLE ref — "add to my library" on an
 * unedited catalog figure records THIS string in the caller's `libraryFigureRefs`
 * (no copy is minted; see library.ts callers in the worker's save-to-library
 * route). A variant's `baseFigureRef` uses the same value for lineage.
 */
export function globalFigureRef(dance: DanceId, figureType: string): string {
  return `global:${dance}:${figureType}`;
}

/**
 * The inverse of {@link globalFigureRef}: recovers `(dance, figureType)` from a
 * catalog ref, or `null` for anything else (an account-figure docRef never has
 * this shape). Used to tell a bookmarked catalog ref apart from a bookmarked
 * account-figure docRef when projecting the library list (§2.7 LibraryEntry).
 */
export function parseGlobalFigureRef(ref: string): { dance: DanceId; figureType: string } | null {
  if (!ref.startsWith("global:")) return null;
  const rest = ref.slice("global:".length);
  const sep = rest.indexOf(":");
  if (sep === -1) return null;
  const dance = rest.slice(0, sep);
  const figureType = rest.slice(sep + 1);
  // Validate the dance segment instead of trusting it — a `global:bogus:x` ref must
  // return null, not a `FigureDoc` with an invalid `dance` (CLAUDE.md §4).
  if (!isDanceId(dance) || !figureType) return null;
  return { dance, figureType };
}

/**
 * Resolve a `global:<dance>:<figureType>` ref back to its bundled catalog figure,
 * or null when the ref isn't a catalog ref / has no matching entry (⟳v5). This is
 * the **bundled-catalog fallback** for variant resolution (§5.2): the client
 * resolves a variant against its base, and when the live base doc isn't at hand
 * (no snapshot base, no open connection) it falls back to the catalog content —
 * always available in the client bundle. Dance ids carry no colon, so splitting on
 * the first two colons recovers (dance, figureType) even for hyphenated types.
 */
export function libraryFigureByRef(ref: string): LibraryFigure | null {
  const match = /^global:([^:]+):(.+)$/.exec(ref);
  if (!match) return null;
  const [, dance, figureType] = match;
  return LIBRARY_FIGURES.find((f) => f.dance === dance && f.figureType === figureType) ?? null;
}

/**
 * The grouped global browse for one filter: a specific dance (delegates to
 * {@link libraryGroupsForDance}) or `"all"` — every dance's figures grouped by
 * figureType, preserving first-seen order. The Library tab's "All" chip renders
 * this; a figureType family can then span several dances (cross-dance identity).
 */
export function libraryGroupsForFilter(filter: DanceId | "all"): LibraryGroup[] {
  if (filter !== "all") return libraryGroupsForDance(filter);
  const groups = new Map<string, LibraryGroup>();
  for (const figure of LIBRARY_FIGURES) {
    const group = groups.get(figure.figureType);
    if (group) group.figures.push(figure);
    else groups.set(figure.figureType, { figureType: figure.figureType, figures: [figure] });
  }
  return [...groups.values()];
}

// Compare two attributes by their meaning (kind/count/role/value), ignoring ids and the
// deletedAt marker — a picked figure copies the library's attribute ids verbatim, but we
// want a content comparison, not an identity one.
const attrKey = (a: Attribute): string =>
  `${a.kind}|${a.count}|${a.role ?? ""}|${JSON.stringify(a.value)}`;

/**
 * True when a placed figure still matches the library figure it was picked from — same
 * (dance, figureType, name) AND the same live attributes. Used to decide whether a figure is
 * an unchanged library pick (so the UI does NOT badge it "custom") versus one the dancer has
 * actually diverged. A figure whose name is not in the catalog (a typed custom figure) never
 * matches.
 */
export function figureMatchesLibraryOrigin(figure: {
  dance: DanceId;
  figureType: string;
  name: string;
  attributes: Attribute[];
}): boolean {
  const origin = LIBRARY_FIGURES.find(
    (l) => l.dance === figure.dance && l.figureType === figure.figureType && l.name === figure.name,
  );
  if (!origin) return false;
  const live = figure.attributes
    .filter((a) => a.deletedAt == null)
    .map(attrKey)
    .sort();
  const base = (origin.attributes ?? []).map(attrKey).sort();
  return live.length === base.length && live.every((v, i) => v === base[i]);
}
