// GENERATED from docs/seed/istd-standard-figures.json + docs/seed/wdsf-standard-figures.json (net-new merged; see scripts/gen-library.mjs)
// Regenerate with scripts/gen-library.mjs. Source: ISTD International Standard
// (Modern Ballroom) syllabus (system of record) + WDSF syllabus timing data.
// ISTD provides identity; WDSF provides timing/start/finish/notes. Net-new WDSF
// figures are appended. Do not edit by hand — regenerate instead.
import type { DanceId } from "./dances";

export interface LibraryFigureData {
  dance: DanceId;
  figureType: string;
  name: string;
  timing?: string;
  start?: string;
  finish?: string;
  notes?: string[];
}

/** 204 canonical figures across the five Standard dances. */
export const LIBRARY_FIGURE_DATA: readonly LibraryFigureData[] = [
  { dance: "waltz", figureType: "back-lock", name: "Back Lock" },
  {
    dance: "waltz",
    figureType: "back-whisk",
    name: "Back Whisk",
    timing: "123",
    start: "LF bwd in CBMP (Outside Partner Position)",
    finish: "LF crosses behind RF (Promenade Position)",
    notes: [
      "NOTE - Quantity of Turn: May be turned up to 3/8 to R",
      "NOTE-Foot Placement/Couple Position: may start LF bwd in Closed Position",
    ],
  },
  {
    dance: "waltz",
    figureType: "backward-lock",
    name: "Backward Lock",
    timing: "12&3",
    start: "LF bwd in CBMP (Outside Partner Position)",
    finish: "RF diag, bwd (Closed Position)",
    notes: ["NOTE - Foot Placement/Couple Position: may start LF bwd in Closed Position"],
  },
  {
    dance: "waltz",
    figureType: "basic-weave",
    name: "Basic Weave",
    timing: "123 123",
    start: "RF bwd (Closed Position)",
    finish: "LF to side and slightly fwd (Closed Position)",
    notes: [
      "NOTE - General: steps 1-3 or 4-6 only may be used.",
      "NOTE-Couple Position: may end in Promenade Position",
    ],
  },
  {
    dance: "waltz",
    figureType: "chasse-from-pp",
    name: "Chassé from PP",
    timing: "12&3",
    start: "RF fwd and across in CBMP (Promenade Position)",
    finish: "LF to side and slightly fwd (Closed Position)",
    notes: [],
  },
  {
    dance: "waltz",
    figureType: "closed-change-on-lf",
    name: "Closed Change on LF",
    timing: "123",
    start: "LF fwd (Closed Position)",
    finish: "LF closes to RF",
    notes: [],
  },
  {
    dance: "waltz",
    figureType: "closed-change-on-rf",
    name: "Closed Change on RF",
    timing: "123",
    start: "RF fwd (Closed Position)",
    finish: "RF closes to LF (Closed Position)",
    notes: [],
  },
  { dance: "waltz", figureType: "closed-changes", name: "Closed Changes" },
  { dance: "waltz", figureType: "closed-impetus", name: "Closed Impetus" },
  { dance: "waltz", figureType: "closed-telemark", name: "Closed Telemark" },
  { dance: "waltz", figureType: "closed-wing", name: "Closed Wing" },
  { dance: "waltz", figureType: "contra-check", name: "Contra Check" },
  {
    dance: "waltz",
    figureType: "cross-hesitation-from-pp",
    name: "Cross Hesitation from PP",
    timing: "1 (23)",
    start: "RF fwd in CBMP (Promenade Position)",
    finish: "Weight on RF",
    notes: ["NOTE - Quantity of Turn: may turn up to ¼ to L (Man)"],
  },
  {
    dance: "waltz",
    figureType: "double-reverse-spin",
    name: "Double Reverse Spin",
    timing: "123 (12&3 Lady)",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "Weight on RF",
    notes: [
      "NOTE - Quantity of Turn: may turn between ¾ and 1 full turn to L",
      "NOTE- Timing: alternative timing of 123& may be used for the Lady",
    ],
  },
  {
    dance: "waltz",
    figureType: "drag-hesitation",
    name: "Drag Hesitation",
    timing: "123",
    start: "LF Fwd and slightly to side (Closed Position)",
    finish: "LF closes to RF w/o weight, weight on RF (Closed Position)",
    notes: ["NOTE - Foot Placement/ Couple Position: may start LF Fwd in CBMP in Wing Position"],
  },
  {
    dance: "waltz",
    figureType: "fallaway-reverse-and-slip-pivot",
    name: "Fallaway Reverse and Slip Pivot",
    timing: "123&",
    start: "LF fwd and slightly to side (Closed position)",
    finish: "RF bwd (Slip Pivot) weight on RF, LF held in position (Closed Position)",
    notes: [
      "NOTE- Foot Placement/Couple Position: May start with LF fwd in CBMP in Wing Position.",
      "NOTE- Quantity of Turn: may be danced with less or no turn (when danced into a corner).",
      "NOTE - Timing: alternative timings of 12&3 or 123& may be used",
    ],
  },
  { dance: "waltz", figureType: "fallaway-whisk", name: "Fallaway Whisk" },
  {
    dance: "waltz",
    figureType: "hesitation-change",
    name: "Hesitation Change",
    timing: "123",
    start: "LF bwd and slightly to side (Closed Position)",
    finish: "LF closes to RF w/o weight-weight on RF (Closed Position)",
    notes: [
      "NOTE - Foot Placement/Couple Position: may start LF bwd in CBMP in Outside Partner Position",
    ],
  },
  {
    dance: "waltz",
    figureType: "hover-corte",
    name: "Hover Corté",
    timing: "123",
    start: "RF bwd and slightly to side (Closed Position)",
    finish: "Transfer weight to RF (Closed Position)",
    notes: [
      "NOTE - Timing: alternative timing using 2 bars of music may be used (123 123).",
      "NOTE - Couple Position: it may start in Promenade Position",
    ],
  },
  {
    dance: "waltz",
    figureType: "impetus",
    name: "Impetus",
    timing: "123",
    start: "LF bwd and slightly to side (Closed Position)",
    finish: "LF to side and slightly Bwd (Closed Position)",
    notes: [
      "NOTE - Foot Placement/ Couple Position: it may start LF Bwd in CBMP in Outside Partner Position",
    ],
  },
  {
    dance: "waltz",
    figureType: "impetus-to-pp",
    name: "Impetus to PP",
    timing: "123",
    start: "LF Bwd and slightly to side (Closed Position)",
    finish: "LF diag Fwd L side leading (Promenade Position)",
    notes: [
      "NOTE - Foot Placement/ Couple Position: it may start LF Bwd in CBMP in Outside Partner Position",
    ],
  },
  { dance: "waltz", figureType: "left-whisk", name: "Left Whisk" },
  {
    dance: "waltz",
    figureType: "natural-spin-turn",
    name: "Natural Spin Turn",
    timing: "123 123",
    start: "RF fwd (Closed Position)",
    finish: "LF bwd and slightly to side (Closed Position)",
    notes: [
      "NOTE - Foot Placement/Couple Position: it may start RF fwd in CBMP in Outside Partner Position",
      "NOTE - Quantity of Turn: may be underturned to end backing DC against LOD or overturned to end",
    ],
  },
  {
    dance: "waltz",
    figureType: "natural-turn",
    name: "Natural Turn",
    timing: "123 123",
    start: "RF fwd (Closed Position)",
    finish: "LF closes to RF",
    notes: [
      "NOTE - General: Steps 1-3 or 4-6 only may be used",
      "NOTE- Foot Placement/Couple Position: May start with RF fwd in CBMP in Outside Partner Position.",
    ],
  },
  {
    dance: "waltz",
    figureType: "natural-turning-lock",
    name: "Natural Turning Lock",
    timing: "1&23",
    start: "RF bwd with R side leading (Closed Position)",
    finish: "LF diag. fwd L side leading (Promenade Position)",
    notes: [
      "NOTE - Couple Position/ Foot Placement: may end in Closed Position, the following step is taken RF",
      "NOTE- Quantity of Turn/ Couple Position: may overturn to end backing DC in Closed position.",
    ],
  },
  {
    dance: "waltz",
    figureType: "open-impetus-and-cross-hesitation",
    name: "Open Impetus and Cross Hesitation",
  },
  { dance: "waltz", figureType: "open-impetus-and-wing", name: "Open Impetus and Wing" },
  {
    dance: "waltz",
    figureType: "open-telemark-and-cross-hesitation",
    name: "Open Telemark and Cross Hesitation",
  },
  { dance: "waltz", figureType: "open-telemark-and-wing", name: "Open Telemark and Wing" },
  {
    dance: "waltz",
    figureType: "outside-change",
    name: "Outside Change",
    timing: "123",
    start: "LF bwd in CBMP (Outside Partner Position)",
    finish: "LF to side and slightly fwd (Closed Position)",
    notes: [
      "NOTE - Foot Placement/Couple Position: may end in Promenade position. It may start LF Bwd in",
    ],
  },
  {
    dance: "waltz",
    figureType: "outside-spin",
    name: "Outside Spin",
    timing: "123",
    start: "LF Bwd in CBMP (small step)",
    finish: "LF to side",
    notes: [
      "NOTE - Quantity of Turn: may be underturned (no Pivot on step3) in which case the exit is RF bwd",
    ],
  },
  {
    dance: "waltz",
    figureType: "progressive-chasse-to-r",
    name: "Progressive Chassé to R",
    timing: "12&3",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "RF to side and slightly bwd (Closed Position)",
    notes: [
      "NOTE- Foot Placement/Couple Position: May start with LF fwd in CBMP in Wing Position.",
    ],
  },
  {
    dance: "waltz",
    figureType: "quick-open-reverse",
    name: "Quick Open Reverse",
    timing: "1&23",
    start: "RF fwd in CBMP (Outside Partner position)",
    finish: "LF bwd in CBMP (Outside Partner position)",
    notes: [
      "NOTE - General: dance steps 1-4 of Quick Open Reverse Turn.",
      "NOTE - Couple Position: may start in promenade Position.",
    ],
  },
  { dance: "waltz", figureType: "reverse-corte", name: "Reverse Corté" },
  {
    dance: "waltz",
    figureType: "reverse-pivot",
    name: "Reverse Pivot",
    timing: "&",
    start: "RF diag, bwd outside Lady’s LF (Closed Position)",
    finish: "weight on RF (Closed Position)",
    notes: [],
  },
  {
    dance: "waltz",
    figureType: "reverse-turn",
    name: "Reverse Turn",
    timing: "123 123",
    start: "LF fwd (Closed Position)",
    finish: "RF closes to LF",
    notes: [
      "NOTE - General: Steps 1-3 or 4-6 only may be used",
      "NOTE- Foot Placement/Couple Position: May start with LF fwd in CBMP in Wing Position.",
    ],
  },
  {
    dance: "waltz",
    figureType: "reverse-turning-lock",
    name: "Reverse Turning Lock",
    timing: "1&23",
    start: "RF bwd with R side leading (Closed Position)",
    finish: "LF to side and slightly fwd (Closed Position)",
    notes: ["NOTE - Couple Position: may end in Promenade Position"],
  },
  {
    dance: "waltz",
    figureType: "running-cross-chasse",
    name: "Running Cross Chasse",
    timing: "1&23",
    start: "RF fwd in CBMP (Outside Partner position)",
    finish: "LF fwd L side leading (Closed Position)",
    notes: [
      "NOTE - Couple Position: may start and end in promenade Position.",
      "NOTE - Timing: alternative timing of 12&3 may be used.",
    ],
  },
  {
    dance: "waltz",
    figureType: "running-finish",
    name: "Running Finish",
    timing: "123",
    start: "LF bwd in CBMP (Outside Partner Position)",
    finish: "LF fwd L side leading (Closed Position)",
    notes: ["NOTE - Couple Position: may end in Promenade Position"],
  },
  {
    dance: "waltz",
    figureType: "running-spin-turn",
    name: "Running Spin Turn",
    timing: "123 1&23",
    start: "RF fwd (Closed Position)",
    finish: "RF bwd R side leading (Closed Position)",
    notes: [
      "NOTE - Timing: alternative timing of 123 112&3 may be used.",
      "NOTE-Foot Placement/ Couple Position: May start RF fwd in CBMP in Outside Partner Position",
    ],
  },
  {
    dance: "waltz",
    figureType: "telemark",
    name: "Telemark",
    timing: "123",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "LF to side and slightly fwd (Closed Position)",
    notes: ["NOTE -Foot Placement/ Couple Position: it may start LF Fwd in CBMP in Wing Position"],
  },
  {
    dance: "waltz",
    figureType: "telemark-to-pp",
    name: "Telemark to PP",
    timing: "123",
    start: "LF Fwd and slightly to side (Closed Position)",
    finish: "LF to side (Promenade Position)",
    notes: ["NOTE -Foot Placement/ Couple Position: it may start LF fwd in CBMP in Wing Position"],
  },
  { dance: "waltz", figureType: "turning-lock", name: "Turning Lock" },
  { dance: "waltz", figureType: "turning-lock-to-r", name: "Turning Lock to R" },
  {
    dance: "waltz",
    figureType: "weave-from-pp",
    name: "Weave from PP",
    timing: "123 123",
    start: "RF fwd and across in CBMP (Promenade Position)",
    finish: "LF to side and slightly fwd (Closed Position)",
    notes: [
      "NOTE - General: steps 1-3 or 4-6 only may be used.",
      "NOTE - Couple Position: may end in Promenade position",
    ],
  },
  {
    dance: "waltz",
    figureType: "whisk",
    name: "Whisk",
    timing: "123",
    start: "LF fwd (Closed Position)",
    finish: "LF crosses behind RF (Promenade Position)",
    notes: [
      "NOTE - Quantity of Turn: may turn up to ¼ to L",
      "NOTE - Foot Placement/Couple Position: may start LF fwd in Wing Position",
    ],
  },
  {
    dance: "waltz",
    figureType: "wing",
    name: "Wing",
    timing: "1 (23)",
    start: "RF fwd in CBMP (Outside Partner Position)",
    finish: "LF closes to RF w/o weight, weight on RF (Wing Position)",
    notes: [],
  },
  {
    dance: "waltz",
    figureType: "wing-from-pp",
    name: "Wing from PP",
    timing: "1 (23)",
    start: "RF fwd and across in CBMP (Promenade Position)",
    finish: "LF closes to RF w/o weight, weight on RF (Wing Position)",
    notes: [],
  },
  { dance: "viennese_waltz", figureType: "backward-change-step", name: "Backward Change Step" },
  { dance: "viennese_waltz", figureType: "contra-check", name: "Contra Check" },
  { dance: "viennese_waltz", figureType: "forward-change-step", name: "Forward Change Step" },
  {
    dance: "viennese_waltz",
    figureType: "lf-backward-change-step-natural-to-reverse",
    name: "LF Backward Change Step Natural to Reverse",
    timing: "123",
    start: "LF bwd (Closed Position)",
    finish: "RF closes to LF (Closed Position)",
    notes: [],
  },
  {
    dance: "viennese_waltz",
    figureType: "lf-forward-change-step-reverse-to-natural",
    name: "LF Forward Change Step Reverse to Natural",
    timing: "123",
    start: "LF fwd (Closed Position)",
    finish: "LF closes to RF",
    notes: [],
  },
  { dance: "viennese_waltz", figureType: "natural-fleckerl", name: "Natural Fleckerl" },
  {
    dance: "viennese_waltz",
    figureType: "natural-turn",
    name: "Natural Turn",
    timing: "123 123",
    start: "RF fwd (Closed Position)",
    finish: "LF closes to RF (Closed Position)",
    notes: ["NOTE - General: steps 1-3 or 4-6 only may be used."],
  },
  { dance: "viennese_waltz", figureType: "reverse-fleckerl", name: "Reverse Fleckerl" },
  {
    dance: "viennese_waltz",
    figureType: "reverse-turn",
    name: "Reverse Turn",
    timing: "123 123",
    start: "LF fwd (Closed Position)",
    finish: "RF closes to LF (Closed Position)",
    notes: ["NOTE - General: steps 1-3 or 4-6 only may be used."],
  },
  {
    dance: "viennese_waltz",
    figureType: "rf-backward-change-step-reverse-to-natural",
    name: "RF Backward Change Step Reverse to Natural",
    timing: "123",
    start: "LF bwd (Open Opp.; LH to RH and RH to LH hold)",
    finish: "Weight on RF (Open Prom; LH to RH and RH to LH Hold)",
    notes: [
      "NOTE -FOOT ACTION/GENERAL: a series of forward or backward changes may be",
      "NOTE - General: Steps 1-5 or 6 - 10 only may be used.",
      "NOTE -Couple Position: May be danced in Open Opposing Position or Extended Open Opp. Pos.",
      "NOTE - Timing, Foot Placement: When the Time Step is danced using the Guapacha Timing, the foot",
      "NOTE - General: Steps 1-5 or 6 - 10 only may be used.",
      "NOTE -Couple Position: May be danced in Open Opposing position with any appropriate hold.",
      "NOTE - Quantity of turn: Up to ½ turn to L can be made",
      "NOTE - General: Steps 1-3 or 4-6 only may be used.",
      "NOTE -Couple Position: May be danced in Close Opposing Position",
      "NOTE - General Action/ Timing/Hold: Steps 3-5 may be replaced with 3 Cha Cha Locksteps bwd( 4&1",
      "NOTE - Timing: Guapacha Timing may be used.",
      "NOTE - General Action: Cha Cha Chasse to side may be replaced by a Three Step Turn for Man and",
      "NOTE - Timing: Guapacha Timing may be used",
      "NOTE - General Action: Cha Cha Chasse to side may be replaced by a Three Step Turn for Man and",
      "NOTE - General Action: Steps 3-5 may be replaced by a Cha Cha Lockstep fwd (Man) and Cha Cha",
      "NOTE - General Action: Steps 3-5 may be replaced by a Cha Cha Lockstep fwd (Man) and Cha Cha",
      "NOTE - General: Three Cha Cha Chas to R may replace steps 3-5 of Hand to Hand to R, New York to",
      "NOTE - General: Three Cha Cha Chas to L may replace steps 3-5 of Hand to Hand to L, New York to R,",
      "NOTE - General: Steps 1-5 or 6-10 only may be used. Man may dance Lady’s steps and vice versa.",
      "NOTE - Timing: Guapacha Timing may be used.",
      "NOTE - General Action/ Timing: Alternative Ending- after step 5 Man turns ¼ to L (Lady ¼ to R) to",
      "NOTE - Timing: Guapacha Timing may be used.",
      "NOTE - General Action/Couple Position: May end in Open Opp. Pos. Man turns ¼ to L at the end of",
      "NOTE - General: Steps 1-5 or 6 -10 only may be used.",
      "NOTE -Couple Position: May be danced in Open Opposing position",
      "NOTE - Timing: Guapacha Timing may be used.",
      "NOTE - General Action/ Couple Position: The figure may be used as a Foot Change- in this case Lady",
      "NOTE - General: Steps 1-5 or 6-10 only may be used.",
      "NOTE -General Action: Steps 8-10 may be replaced by a Cha Cha Lock fwd or three Cha Cha Locks",
      "NOTE - Timing: Guapacha Timing may be used.",
      "NOTE - General: Steps 1-5 or 6-10 only may be used.",
      "NOTE - General Action: Steps 8-10 may be replaced by a Cha Cha Lock fwd or three Cha Cha Locks",
      "NOTE - Lead/ Hold/ Shaping: It may be danced with RH to RH Hold, changing to LH to RH hold on",
      "NOTE - General Action/ Couple Position: The figure may be used as a Foot Change- in this case Lady",
      "NOTE - General: Steps 1-5 or 6-10 only may be used.",
      "NOTE - General Action: Steps 8-10 may be replaced by a Cha Cha Lock fwd or three Cha Cha Locks",
      "NOTE - Lead/ Hold/ Shaping: It may be danced with RH to RH Hold, changing to LH to RH hold on",
      "NOTE - General Action: Ronde Chasse may be replaced by Slip Close Chasse.",
      "NOTE - General Action: Ronde Chasse may be replaced by Slip Close Chasse.",
      "NOTE - Quantity of Turn/ General Action: Lady may dance a Spiral Cross on step 7 and continue with",
      "NOTE_ General: Steps 6-10 only may be used.",
      "NOTE - General Action: Man’s step 6 may be danced as a Bwd Walk and step 7 as a Side Walk.",
      "NOTE -General Action/Couple Position: Steps 8 -10 may be replaced by a side Chasse for Man and",
      "NOTE - General: Steps 6-10 only may be used.",
      "NOTE - General Action: Man’s step 6 may be danced a s a bwd Walk and step 7 as a side Walk.",
      "NOTE - General Action/Couple Position: Steps 8 -10 may be replaced by a side Chasse for Man and",
      "NOTE - General: Steps 1-10 or 11-15 only may be used.",
      "NOTE - General Action/Couple Position: Steps 13-15 may be replaced by a side Chasse for Man and",
      "NOTE - General: Steps 6-10 only may be used.",
      "NOTE - General Action: Steps 3-5 for Man may be replaced by a bwd Lockstep.",
      "NOTE - Timing: Guapacha timing may be used.",
      "NOTE - General Action: Steps 3-5 for Man may be replaced by a bwd Lockstep.",
      "NOTE - General Action/Couple Position: Steps 8-10 for the Man may be replaced by a fwd Lockstep",
      "NOTE - Timing: Guapacha timing may be used.",
      "NOTE - General: Steps 6-10 only may be used.",
      "NOTE - General Action: Steps 3-5 for Man may be replaced by a bwd Lockstep. Steps 8-10 may be",
      "NOTE - Timing: Guapacha timing may be used.",
      "NOTE - General Action/Couple Position: Man may replace steps 8-10 with a Hip Twist Chasse (Lady",
      "NOTE - Couple Position: May start in R Side Same Position and end in Open Opp. Position",
      "NOTE - General Action/ Couple Position: Steps 3-5 will be a Chasse to R for both Man and Lady when",
      "NOTE - General/ Couple Position: Step 2 may be directly followed by step 8, in that case the end",
      "NOTE - General: Split Cuban Break to R is always followed by a Split Cuban Break to L.",
      "NOTE - Timing: The first Split Cuban Break is always danced on 2&3 and the following on 4&1.",
      "NOTE -Couple Position: possible amalgamations",
      "NOTE -General: Split Cuban Break to L is always followed by a Split Cuban Break to R.",
      "NOTE - Timing: The first Split Cuban Break is always danced on 2&3 and the following on 4&1.",
      "NOTE -Couple Position: possible amalgamations",
      "NOTE - Couple Position: Possible amalgamations",
      "NOTE - Couple Position: Possible amalgamations",
      "NOTE - General: Steps -6-10 only may be used.",
      "NOTE - General Action/ Couple Position: It may end in Fan L Angle Position. Lady overturns Spiral",
      "NOTE - General: Steps 6-10 only may be used.",
      "NOTE - General Action/ Couple Position: It may end in Fan L Angle Position. Lady overturns Spiral",
      "NOTE - Timing: Guapacha timing may be used",
      "NOTE - General: Steps 11- 20 may be omitted.",
      "NOTE - General Action: Steps 28-30 may be replaced by 3 fwd Locksteps (Man), 3 bwd Locksteps",
      "NOTE - Timing: Guapacha timing may be used",
      "NOTE - General: Steps 6 - 15 may be omitted.",
      "NOTE - General Action/ Timing/ Couple Position: At the end of step 15 as the Lady ends in R Diag.",
      "NOTE - General: Man may replace steps 1-2 with steps 16-17.",
      "NOTE - General Action: Lady’s steps 18-26 may be replaced by Three Cha Cha Locks Bwd.",
      "NOTE - General/Couple Position:",
      "NOTE - General: Steps 6-10 only may be used.",
      "NOTE -General Action/Quantity of Turn/Couple Position: Man may turn ¼ to L on steps 7-9 to end",
      "NOTE - General Action/ Couple Position: The figure may be used as a Foot Change- in this case Lady",
      "NOTE - General: Steps 1-5 or 6-10 only may be used.",
      "NOTE -General Action/Quantity of Turn/Couple Position: Man may turn ¼ to L on steps 7 and dance",
      "NOTE - General Action/ Couple Position: The figure may be used as a Foot Change- in this case Lady",
      "NOTE -General Action/Couple Position: Steps 8-10 may be replaced with a Cha Cha Chasse to side",
      "NOTE -General Action/Couple Position: Lady may replace step 3 with a Forward Walk Turning to end",
      "NOTE -General Action/Couple Position: Lady may replace step 3 with a Forward Walk Turning to end",
      "NOTE - General Action: steps 3-5 may be replaced with an appropriate form of Cha Cha Chasse",
      "NOTE - Foot Placement: start with feet apart and weight on LF (normally after a Ronde Chasse)",
      "NOTE -Couple Position/ Quantity of Turn: May end in Right Diagonal R Angle Position (Lady will turn",
      "NOTE - Foot Placement: start with feet apart and weight on LF (normally after a Ronde Chasse)",
      "NOTE -Couple Position/ Quantity of Turn/General Action: It may end in Open Opp. Position. Man",
      "NOTE - General: Man may dance Lady’s steps and vice versa. Steps 6-11 only may be danced.",
      "NOTE - General Action: Steps 3-5 may be replaced by a Cha Cha Lock Fwd, steps 6-11 may be replaced",
      "NOTE-General: Steps 6-10 may be replaced by steps 6-10 of Close Hip Twist Spiral, ending in Fan L",
      "NOTE - General: Steps 1-3 or 4-6 only may be used.",
      "NOTE -Couple Position: May be danced in Open Opposing position with appropriate hold",
      "NOTE - General: Steps 1-3 or 4-6 only may be used.",
      "NOTE -Lead-Hold-Shaping: May be danced without hold",
      "NOTE - General: Steps 1-3, 4-6, 7-9 or 10- 12 only may be used. Man may dance Lady’s steps and",
      "NOTE - Couple Position: May end in Open Opp. Position",
      "NOTE - General: Steps 4-6 only may be used.",
      "NOTE - General: Steps 4-6 only may be used",
      "NOTE - General: Steps 1-3 or 4-6 only may be danced Man may close RF to LF on the preceding step",
      "NOTE - General: Steps 1-3 or 4-6 only may be used. Man may dance Lady’s steps and vice versa.",
      "NOTE - General: Steps 4-6 only may be used.",
      "NOTE - Couple position: May start in Open Opp. Position.",
      "NOTE- General Action: Steps 1-2 for Man may be danced as a Cuban Rock Action.",
      "NOTE - General: Steps 4-6 only may be used.",
      "NOTE - Couple position: May start in Open Opp. Position.",
      "NOTE- General Action: Steps 1-2 for Man may be danced as a Cuban Rock Action.",
      "NOTE - General: Steps 4-9 only may be used.",
      "NOTE - General Action: Lady may dance a Spiral Turn on step 6 and then continue as chart.",
      "NOTE - General: Steps 4-9 only may be used.",
      "NOTE - General Action: Lady may dance a Spiral Turn on step 6 and then continue as chart.",
      "NOTE - General Action: Lady may dance a Spiral Cross or Spiral Turn at the end of the preceding step",
      "NOTE - General Action: Steps 1-3 may be danced as a Cucaracha to L. Step 6 may be danced as RF",
      "NOTE - Couple Position/ General Action: Cuban Rocks and Syncopated Cuban Rocks may be danced",
      "NOTE - General: Steps 1-6 only may be used",
      "NOTE - General Action/: Steps 7-8 may be danced by one partner only, the other partner will dance",
      "NOTE - General: Steps 10 - 12 may be replaced by steps 4 -6 of Close Hip twist finished to side.",
      "NOTE - General: Steps 4-6 only may be used.",
      "NOTE - Couple Position: May end in Open Opp. Position",
      "NOTE - Timing: Alternative timing & 4.1 may be used on steps 3 and 4",
      "NOTE - General: Steps 7-9 only may be used.",
      "NOTE - General Action: Man may lead the Lady to dance a Spiral Action turning to L on step 4 turning",
      "NOTE - General: Steps 4-6 only may be used",
      "NOTE - General Action/ Couple Position: Lady may dance two backward walks on steps 5-6 to finish",
      "NOTE - Couple position: May start in Open Opp. Position. May end in Open Opposing Pos. NOTE -",
      "NOTE - General: Steps 1- 6 only may be used. Steps 7 - 12 may be repeated.",
      "NOTE - General Action/ Hold: When followed by the Spiral, it is danced without hold. Man may",
      "NOTE- General Action / Couple Position:",
      "NOTE - Couple Position: It may end in Open Opp. Position",
      "NOTE- Couple Position: It may end in Open Opp. Position",
      "NOTE - General Action/ Couple Position: Man May dance step 6 as a Side Walk or both dance step 6",
      "NOTE - Couple Position: It may end in Open Opp. Position",
      "NOTE - General: Steps 1-4 only may be used. After step 7 it is possible to follow with steps 4-6 of",
      "NOTE - General: After any figure or part of figure that ends in Open Opp. Position a series of Fwd or",
      "NOTE - General: May start on LF. 2, 4 or 6 steps only may be used.",
      "NOTE - General: Only 2 steps may be danced. It may start on LF.",
      "NOTE - Timing: Alternative timing 12&34 or 1&234 may be used (SYNCOPATED SUR PLACE)",
      "NOTE - General: Steps 1-2 only may be used. May start on LF",
      "NOTE - General: Steps 1-2 only may be used",
      "NOTE - Couple Position: May end in Close PP",
      "NOTE- general Action: Appel may be used on step 1",
      "NOTE - General: Step 1 may be replaced by a step taken Fwd (DEPLACEMENT)",
      "NOTE - General Action: Position held may be used instead of Sur Place during Man’s steps 3-8.",
      "NOTE - General: Steps 5-6 may be repeated",
      "NOTE - General: It may start from step 3 when preceded by a figure that ends in PP.",
      "NOTE - General: It may start from step 3 when preceded by a figure that ends in PP.",
      "NOTE - General: Steps 1-2 only may be used.",
      "NOTE - General: Steps only may be used.",
      "NOTE - General: It may start from step 3 when preceded by a figure that ends in PP.",
      "NOTE - General Action: Position held may be used instead of Sur Place during Man’s steps 8- 16",
      "NOTE - General: It may start from step 3 when preceded by a figure that ends in PP.",
      "NOTE - General: Steps 1-6 only may be danced to end in PP. Steps 3-4 may be repeated or taken out.",
      "NOTE - Couple position: L Diag. Opp. Position (starting position) must be achieved at the end of",
      "NOTE - General: It is possible to dance step 1 followed by steps 6-8 (TELEMARK)",
      "NOTE - General Action: Instead of the Appel on step 1 RF can be slipped bwd (Man) or LF fwd (Lady)",
      "NOTE - General: Steps or only may be danced.",
      "NOTE - General: It may start from step 3 when preceded by a figure that ends in PP.",
      "NOTE - General: Steps 7-8 may be omitted, or repeated",
      "NOTE - General: May start with RF (Man)",
      "NOTE - Timing/ General Action: Alternative timing 1&2&34 may be used (3 taps w/o weight). The",
      "NOTE - General: It may start from step 3 when preceded by a figure that ends in PP.",
      "NOTE - General: Steps 1-3 may be be used as an alternative entry to PP.",
      "NOTE - General Action / Timing: Step (Man and Lady) may be replaced by steps of Sur Place -",
      "NOTE - General Action: Step 1 may be danced as a Weight Transfer in place.",
      "NOTE - General: It may start from step 3 when preceded by a figure that ends in PP.",
      "NOTE - General Action / Timing: Lady may replace steps 4-5 with Continuous Spins Action, adding",
      "NOTE - General: It may start from step 3 when preceded by a figure that ends in PP.",
      "NOTE - General Action / Timing: Lady may replace steps 8 -9 with Continuous Spins Action, adding",
      "NOTE - General: An alternative variation is to dance steps 3-5 (starting from PP or Closed Pos.)Close",
      "NOTE - General: Lady’s steps 5-6 may be replaced by 4 steps of basic movement (5678).",
      "NOTE - General: It may start from step 3 when preceded by a figure that ends in PP.",
      "NOTE - General Action: Man may use Sur Place during Steps 9 - 18",
      "NOTE - General: It may start from step 3 when preceded by a figure that ends in PP.",
      "NOTE - General Action: Man may use Sur Place during Steps 9 - 26.",
      "NOTE - Couple Position: Step 1 may be taken in L Diag. Opp. Position OP.",
      "NOTE - General: Coup de Pique changing from RF to LF may be followed by Coup de Pique changing",
      "NOTE - General: Steps 1-3 or 4-6 only may be used.",
      "NOTE -Timing: If used as a link between Natural and Reverse Roll, alternative timing of SQQ may be",
      "NOTE - General: Steps 1-3 or 4-6 only may be used.",
      "NOTE -Timing: If used as a link between Natural and Reverse Roll, alternative timing of SQQ may be",
      "NOTE - General: Steps 1-3 or 4-6 only may be used.",
      "NOTE - General: Parts of the figure may be used on their own depending on the preceding or",
      "NOTE - Couple Position: May end in PP",
      "NOTE - General: Steps 1-3 or 4-6 only may be used. When dancing a Stationary Samba Walk Man",
      "NOTE - Hold: Normal Hold can be used through this figure.",
      "NOTE - General: Steps 1-3 or 4-6 only may be used.",
      "NOTE - General: Man can start with LF and dance the Lady’s steps and the Lady starts with RF and",
      "NOTE - Quantity of Turn and Couple Position: ¼ to R (Lady L) can be made to finish in Open Opposing",
      "NOTE - General: Steps 1-3 or 4-6 may be used.",
      "NOTE - Timing: Alternative timing SQQ SQQ may be used.",
      "NOTE - Hip Design: The Lady may straighten her knees with pelvis tilted bwd at the end of step 3.",
      "NOTE - General: Steps 1-3, 1-6, 4-6 or 4-9 only may be used.",
      "NOTE - Quantity of turn: It is possible to dance steps 1-3 only, and in this case the Quantity o of turn",
      "NOTE - General: Man may dance Lady’s steps and vice versa.",
      "NOTE - Quantity of turn: May turn up to ¼ to L or R.",
      "NOTE - Couple position: Open Opp (LH to RH Hold or w/o Hold) may also be used.",
      "NOTE - General: Steps 1-3, 4-6 or 4-9 only may be used.",
      "NOTE - General: Steps 1-3 or 1-6 only may be used.",
      "NOTE - General: Steps 1-3 or 4-6 only may be used.",
      "NOTE - General: The last 2 steps of the Criss Cross Volta may be danced as the last 2 steps of a",
      "NOTE - Quantity of turn/Couple position: It can be turned only ¼ to L (Man) and ¼ to R (Lady) to end",
      "NOTE - Couple Position: It may end in Close Opp. Position- Normal Hold",
      "NOTE - General: The last 2 steps of the Criss Cross Volta may be danced as the last 2 steps of a",
      "NOTE - Quantity of turn/Couple position: It can be turned only ¼ to R (Man) and ¼ to L (Lady) to end",
      "NOTE - Couple Position: It may end in Close Opp. Position - Normal Hold",
      "NOTE - General: Steps 2-3 can be repeated. It may start from step 2. The last 2 steps of the Travelling",
      "NOTE - Hold: LH to RH Hold may be used.",
      "NOTE - General: Steps 2-3 can be repeated. It may start from step 2. The last 2 steps of the Travelling",
      "NOTE - Hold: LH to RH Hold may be used.",
      "NOTE - General: Man may at the same time dance the Lady’s steps of Underarm Turn turning L, in",
      "NOTE - General/ Timing: They may both dance a Volta Spot Turn with timing 1a2a3a4 making 2 full",
      "NOTE - Hold: LH to RH Hold may be used.",
      "NOTE - General: Man may at the same time dance the Lady’s steps of Underarm Turn turning L, in",
      "NOTE - General/ Timing: They may both dance a Volta Spot Turn with timing 1a2a3a4 making 2 full",
      "NOTE - Hold: LH to RH Hold may be used.",
      "NOTE - General: The last 2 steps of the Maypole Lady Turning R may be danced as the last 2 steps of",
      "NOTE - Couple position: May end in Close Opp. position",
      "NOTE - General: The last 2 steps of the Maypole Lady Turning L may be danced as the last 2 steps of",
      "NOTE - Couple position: May finish in R Side Same Pos with Both Hand Hold. May end in Close Opp.",
      "NOTE - General: It may start with the RF.",
      "NOTE - General/ Timing: Cruzado Walk on RF may be followed by steps 3-7 of Continuous Cruzados",
      "NOTE - General: Steps 1-3 or 4-6 only may be used.",
      "NOTE - Couple Position: 1-3 of Cruzados Locks may be danced in R Side Same Position",
      "NOTE - General/ Timing: May be danced as a CONTINUOUS CRUZADOS LOCKS (3.4.32) by repeating",
      "NOTE - General: It may be danced starting with RF (Man) and LF (Lady).",
      "NOTE - Hold: LH to RH Hold may be used.",
      "NOTE - General: During steps 1-5 Sway to L (Lady R) may be used.",
      "NOTE - General: During steps 1-5 Sway to R (Lady L) may be used.",
      "NOTE - General: Steps 1-3 or 4-6 only may be used.",
      "NOTE - Hold: Normal Hold or RH to RH (LH to LH) Hold may be used.",
      "NOTE - General: Steps 1-3 or 1-6 only may be used.",
      "NOTE - General: Steps 1-3 or 1-6 only may be used.",
      "NOTE - General: Steps 1-3 or 4-6 only may be used.",
      "NOTE - Quantity of turn: Less turn can be made on steps 1-3 and 4-6.",
      "NOTE - Couple Position: Bodies are in contact.",
      "NOTE - General: Steps 1-3 or 4-6 only may be used.",
      "NOTE - Couple Position: Bodies are in contact.",
      "NOTE - General: Steps 1-3 or 4-6 only may be used.",
      "NOTE - General: Steps 1-3, 4-6 or 1-6 only may be used.",
      "NOTE - General: Steps 1-3 or 4-6 only may be used.",
      "NOTE - General: Plait may start with RF (Man) and LF (Lady)",
      "NOTE - Lead-Hold-Shaping: When Plait is preceded by a figure that ends in Normal hold, the change",
      "NOTE - General: After step 7, Man may dance Lady’s steps 1-7 (Lady dances Man’s steps 1-7).",
      "NOTE - Lead-Hold-Shaping: LH for Man and RH for Lady may be lowered",
      "NOTE - General: In this type of Corta Jaca it is possible to repeat steps 1-4.",
      "NOTE - Timing: Alternative Timing may be used (QQS QQS QQS or SaS SaS SaS)",
      "NOTE - Foot Placement: Step 1 can be taken FWD between Lady’s feet. When taken to side (RF Man,",
      "NOTE - General Action: On steps 1 and 7 the Lady may finish in a Spiral Cross Position.",
      "NOTE- Couple Position: It may start in Close Opposing and Open Opposing Position.",
      "NOTE - General: Man’s steps 4-6 and Lady’s 5-8 may be substituted with a foot change to end in R",
      "NOTE - Foot Placement: After step 4, Lady can dance steps 5-6-7 diag. Fwd and make an additional",
      "NOTE - General: Man may dance the Lady’s steps and vice versa.",
      "NOTE - Timing: Alternative timing aS aS may be used",
      "NOTE - General: May start from step 4. Steps 1-6, 1-9 or 4-9 only may be used.",
      "NOTE - General: Kick Ball Change may be used in place of Rhytm Bounce by both Man and Lady",
      "NOTE - General: Lady dances Volta Spot Turn to R or L, Botafogo on RF, Botafogo on LF or Three Step",
      "NOTE - Quantity of turn: The Quantity of Turn may vary depending on the preceding and following",
      "NOTE - General: General: Lady dances Volta Spot Turn to R or L, Botafogo on RF, Botafogo on LF or",
      "NOTE - Quantity of turn: The Quantity of Turn may vary depending on the preceding and following",
      "NOTE - General: General: Lady dances Volta Spot Turn to R or L, Botafogo on RF, Botafogo on LF or",
      "NOTE - Quantity of turn: The Quantity of Turn may vary depending on the preceding and following",
      "NOTE - General: May start from step 3.",
      "NOTE - Couple position/Lead-Hold-Shaping: This figure may be danced in Open Opp. with LH to RH",
      "NOTE - General: May start from step 3.",
      "NOTE - Couple position/Lead-Hold-Shaping: This figure may be danced in Open Opp with LH to RH",
      "NOTE - General: May start from step 3.",
      "NOTE - General: May start from step 3.",
      "NOTE - Lead-Hold-Shaping: RH to RH Hold may be used. In this case the RH to RH Hold may pass over",
      "NOTE - Couple position/ General Action: Steps 6-8 may be replaced by a Jive Ronde Chasse (both",
      "NOTE - General: May start from step 3.",
      "NOTE - Lead-Hold-Shaping: LH to RH Hold may be used. Lady may turn under Man’s LH or RH on step",
      "NOTE - General: May start from step 3.",
      "NOTE - Lead-Hold-Shaping: Alternatively man may place Lady’s RH on his waist on step 5, release the",
      "NOTE - General: Steps 1-5 only may be used.",
      "NOTE - General: More or less turn may be made.",
      "NOTE - General: Steps 3-5 or 3-8 may be repeated. It may start from step 3.",
      "NOTE - General: Steps 3-4 or 3-6 may be repeated. It may start from step 3.",
      "NOTE - Quantity of turn: It may turn up to ¼ to L",
      "NOTE - General: May start from step 3.",
      "NOTE - Couple position: May start in Open Opposing Position with LH to RH or RH to RH Hold.",
      "NOTE - General Action: Man may replace the Rock Action (steps 1-2) with a Side Rock",
      "NOTE - General: May start from step 3.",
      "NOTE - General: May start from step 3.",
      "NOTE - General: Steps 1-2 may be repeated.",
      "NOTE - General: May start from step 3.",
      "NOTE - General: Steps 6-7 may be repeated",
      "NOTE - General Action: Man may replace the Rock Action (steps 1-2) with a Side Rock",
      "NOTE - General: May be followed by a Jive Chasse to side as a choreographic link.",
      "NOTE - Couple position/Lead-Hold-Shaping: Steps 1-2 may also be danced in Normal Hold in Close",
      "NOTE - General: It may start from step 3.",
      "NOTE - Couple position: May start in Open Opposing Position with LH to RH Hold or RH to RH Hold",
      "NOTE - General Action: Lady may replace steps 3-5 with a Running Chasse or Chasse Fwd. Man may",
      "NOTE - General: May start from step 3.",
      "NOTE - Lead-Hold-Shaping: Man may release hold on step 2. He puts the RH on Lady’s back or",
      "NOTE - General: It may start from step 3. Steps 3-4 may be replaced by a Jive Chasse.",
      "NOTE - General: It may start from step 3.",
      "NOTE - General Action: Lady may dance a Running Chasse action on steps 3-5.",
      "NOTE - General: Steps 1-11 or 12-22 only may be used.",
      "NOTE - General Action: Flicks may be replaced by a Kicking action.",
      "NOTE - General: Steps 1-8 or 9-16 only may be used.",
      "NOTE - General: Steps 1-2 may be repeated",
      "NOTE - Timing: This figure may be danced QQQQ or SSQQQQ repeating steps 3 and 4. Any other",
      "NOTE - Lead-Hold-Shaping: RH to LH Hold may be used through this figure. Double Hold may also be",
      "NOTE - General Action/Quantity of turn: The Lady may be lead to increase the Quantity of Turn over",
      "NOTE - Couple Position/ General Action: may start in Open Same Position or L Side Same position.",
      "NOTE - General: RH to RH Hold or RH to LH Hold may be used",
      "NOTE - General: Steps 3-8 may be repeated",
      "NOTE - General Action/ Timing: Last step may be followed by a Break Action timed (1)a2",
      "NOTE - Timing: The following alternative timing may be used: QQ QQQ QQQ.",
      "NOTE - General: May start from step 4.",
      "NOTE - General Action: Steps 1-3 may be replaced by Rock Action or/and by 2 steps taken slightly",
      "NOTE - General Action: Man and lady may dance a Ronde Chasse on Steps 6-8.",
      "NOTE - General: Steps 9-14 may be repeated. Steps 1-14 only may be used. Steps 15-20 may be",
      "NOTE - General Action: Lady may substitute steps 9-14 with a series of Flick Ball Change steps with",
      "NOTE - General: Steps 9-14 may be repeated.",
      "NOTE - Lead/Hold/Shaping: may be danced with double hold, releasing the hold on step 17",
      "NOTE - General Action: When the LF is kicked (jumping action of the standing leg) it is called KICK",
    ],
  },
  {
    dance: "viennese_waltz",
    figureType: "rf-forward-change-step-natural-to-reverse",
    name: "RF Forward Change Step Natural to Reverse",
    timing: "123",
    start: "RF fwd (Closed Position)",
    finish: "RF closes to LF",
    notes: [],
  },
  {
    dance: "quickstep",
    figureType: "back-whisk",
    name: "Back Whisk",
    timing: "SSS",
    start: "LF bwd in CBMP (Outside Partner Position)",
    finish: "LF crosses behind RF (Promenade Position)",
    notes: [
      "NOTE - Timing: Alternative timing SQQ may be used",
      "NOTE - Couple Position: Step 1may be taken bwd in Closed Position",
    ],
  },
  {
    dance: "quickstep",
    figureType: "backward-lock",
    name: "Backward Lock",
    timing: "SQQS",
    start: "LF bwd in CBMP (Outside Partner Position)",
    finish: "RF diag bwd (Closed Position)",
    notes: [
      "NOTE - General: Steps 2-4 only may be used",
      "NOTE - Couple Position: Step 1 may be LF bwd in Closed Position",
    ],
  },
  { dance: "quickstep", figureType: "change-of-direction", name: "Change of Direction" },
  { dance: "quickstep", figureType: "chasse-reverse-turn", name: "Chassé Reverse Turn" },
  { dance: "quickstep", figureType: "closed-impetus", name: "Closed Impetus" },
  { dance: "quickstep", figureType: "closed-telemark", name: "Closed Telemark" },
  {
    dance: "quickstep",
    figureType: "cross-chasse",
    name: "Cross Chassé",
    timing: "SQQ",
    start: "LF fwd (Closed Position)",
    finish: "LF closes to RF (Closed Position)",
    notes: [],
  },
  {
    dance: "quickstep",
    figureType: "cross-swivel",
    name: "Cross Swivel",
    timing: "SS",
    start: "LF fwd (Closed Position)",
    finish: "RF almost closes to LF slightly bwd without weight, weight on RF (Closed Position)",
    notes: [],
  },
  {
    dance: "quickstep",
    figureType: "double-reverse-spin",
    name: "Double Reverse Spin",
    timing: "SSS",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "Weight on RF, LF closes to RF without weight (Closed Position)",
    notes: [],
  },
  {
    dance: "quickstep",
    figureType: "fisht-tail",
    name: "Fisht Tail",
    timing: "SQQ QQS",
    start: "RF fwd in CBMP (Outside Partner Position)",
    finish: "LF fwd and slightly leftwards (Closed Position)",
    notes: ["NOTE- Quantity of turn: it may be danced without turn."],
  },
  { dance: "quickstep", figureType: "fishtail", name: "Fishtail" },
  {
    dance: "quickstep",
    figureType: "forward-lock",
    name: "Forward Lock",
    timing: "SQQS",
    start: "RF fwd in CBMP (Outside Partner Position)",
    finish: "LF diag fwd (Closed Position)",
    notes: [
      "NOTE - General: Steps 2-4 only may be used.",
      "NOTE - Couple Position: Step 1 may be RF fwd in Closed Position",
    ],
  },
  {
    dance: "quickstep",
    figureType: "four-quick-run",
    name: "Four Quick Run",
    timing: "SQQQQS",
    start: "RF bwd and slightly to side (Closed Position)",
    finish: "LF fwd and slightly leftward (Closed Position)",
    notes: [],
  },
  { dance: "quickstep", figureType: "heel-pivot", name: "Heel Pivot (Quarter Turn to Left)" },
  {
    dance: "quickstep",
    figureType: "hover-corte",
    name: "Hover Corté",
    timing: "SSS",
    start: "RF bwd (Closed Position)",
    finish: "transfer weight to RF (Closed Position)",
    notes: ["NOTE- Couple Position: may start in Promenade Position"],
  },
  {
    dance: "quickstep",
    figureType: "impetus",
    name: "Impetus",
    timing: "SSS",
    start: "LF bwd and slightly to side (Closed Position)",
    finish: "LF to side and slightly bwd (Closed Position)",
    notes: [
      "NOTE - Couple Position: Step 1 may be taken bwd in CBMP in Outside Partner Position",
      "NOTE - Timing: Alternative timing SQQ may be used",
    ],
  },
  {
    dance: "quickstep",
    figureType: "impetus-to-pp",
    name: "Impetus to PP",
    timing: "SSS",
    start: "LF bwd and slightly to side (Closed Position)",
    finish: "LF diag. fwd L side leading (Promenade Position)",
    notes: [
      "NOTE - Couple Position: Step 1 may be taken bwd in CBMP in Outside Partner Position",
      "NOTE - Timing: Alternative timing SQQ may be used",
    ],
  },
  {
    dance: "quickstep",
    figureType: "natural-pivot",
    name: "Natural Pivot",
    timing: "S",
    start: "LF bwd and slightly to side (Closed Position)",
    finish: "Weight on LF, RF held in position in Closed Position",
    notes: [],
  },
  { dance: "quickstep", figureType: "natural-pivot-turn", name: "Natural Pivot Turn" },
  {
    dance: "quickstep",
    figureType: "natural-spin-turn",
    name: "Natural Spin Turn",
    timing: "SQQ SSS",
    start: "RF fwd (Closed Position)",
    finish: "LF bwd and slightly to side (Closed Position)",
    notes: [
      "NOTE - Couple Position: May start RF fwd in CBMP in Outside Partner Position",
      "NOTE - Timing: Alternative timing SQQ SQQ may be used",
      "NOTE - Quantity of Turn: It may be underturned (ending backing DC against LOD) or overturned",
    ],
  },
  {
    dance: "quickstep",
    figureType: "natural-turn",
    name: "Natural Turn",
    timing: "SQQ",
    start: "RF fwd (Closed Position)",
    finish: "RF closes to LF (Closed Position)",
    notes: ["NOTE - Couple Position: May start RF fwd in CBMP in Outside Partner Position"],
  },
  {
    dance: "quickstep",
    figureType: "natural-turn-and-back-lock",
    name: "Natural Turn and Back Lock",
  },
  {
    dance: "quickstep",
    figureType: "natural-turn-with-hesitation",
    name: "Natural Turn with Hesitation",
  },
  {
    dance: "quickstep",
    figureType: "open-reverse-turn-quick-open-reverse",
    name: "Open Reverse Turn (quick Open Reverse)",
    timing: "SQQ",
    start: "LF fwd (Closed Position)",
    finish: "LF bwd in CBMP (Outside Partner Position)",
    notes: [],
  },
  { dance: "quickstep", figureType: "progressive-chasse", name: "Progressive Chassé" },
  {
    dance: "quickstep",
    figureType: "progressive-chasse-to-l",
    name: "Progressive Chasse to L",
    timing: "SQQS",
    start: "RF back and slightly to side (Closed Position)",
    finish: "LF to side and slightly fwd (Closed Position)",
    notes: [],
  },
  {
    dance: "quickstep",
    figureType: "progressive-chasse-to-r",
    name: "Progressive Chassé to R",
    timing: "SQQS",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "RF to side and slightly Bwd (Closed Position)",
    notes: [],
  },
  {
    dance: "quickstep",
    figureType: "quarter-turn-to-r",
    name: "Quarter Turn to R",
    timing: "SQQS",
    start: "RF fwd (Closed Position)",
    finish: "LF to side and slightly bwd (Closed Position)",
    notes: ["NOTE - Couple Position: may start RF fwd in CBMP in Outside Partner Position"],
  },
  { dance: "quickstep", figureType: "quick-open-reverse", name: "Quick Open Reverse" },
  {
    dance: "quickstep",
    figureType: "reverse-pivot",
    name: "Reverse Pivot",
    timing: "S",
    start: "RF diag bwd (Closed Position)",
    finish: "Weight on RF (Closed Position)",
    notes: [],
  },
  {
    dance: "quickstep",
    figureType: "reverse-turn",
    name: "Reverse Turn",
    timing: "SQQ",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "LF closes to RF (Closed Position)",
    notes: [],
  },
  {
    dance: "quickstep",
    figureType: "rumba-cross",
    name: "Rumba Cross",
    timing: "QQS",
    start: "LF fwd, long step (Closed Position)",
    finish: "LF to side and slightly bwd, weight on LF -Pivot (Closed Position)",
    notes: [],
  },
  {
    dance: "quickstep",
    figureType: "running-cross-chasse",
    name: "Running Cross Chasse",
    timing: "SQQS",
    start: "RF fwd in CBMP (Outside Partner position)",
    finish: "LF fwd L side leading (Closed Position)",
    notes: ["NOTE- Couple Position: It may end in Promenade Position"],
  },
  {
    dance: "quickstep",
    figureType: "running-finish",
    name: "Running Finish",
    timing: "SQQ",
    start: "LF bwd in CBMP (Outside Partner Position)",
    finish: "LF fwd L side leading (Closed Position)",
    notes: [
      "NOTE - Timing: Alternative timing QQS may be used",
      "NOTE - Couple Position: It may end in PP",
    ],
  },
  {
    dance: "quickstep",
    figureType: "running-natural-turn",
    name: "Running Natural Turn",
    timing: "SQQ SSSS QQS",
    start: "RF fwd (Closed Position)",
    finish: "LF fwd L side leading (Closed Position)",
    notes: [
      "NOTE - Foot Placement/Couple Position: May start RF fwd in CBMP in OP Position.",
      "NOTE-General: steps 1-4 or1-7 only may be used",
      "NOTE-Timing: alternative timing of SQQ SQQ may be used on steps 5-10",
    ],
  },
  { dance: "quickstep", figureType: "running-right-turn", name: "Running Right Turn" },
  {
    dance: "quickstep",
    figureType: "running-spin-turn",
    name: "Running Spin Turn",
    timing: "SSQQS",
    start: "RF fwd (Closed Position)",
    finish: "RF bwd R side leading (Closed Position)",
    notes: [
      "NOTE-Foot Placement/ Couple Position: May start RF fwd in CBMP in Outside Partner Position",
    ],
  },
  {
    dance: "quickstep",
    figureType: "six-quick-run",
    name: "Six Quick Run",
    timing: "QQQQQQ",
    start: "RF bwd and slightly to side (Closed Position)",
    finish: "LF fwd and slightly leftward (Closed Position)",
    notes: ["NOTE-General: due to the fast timing a slight jumping action may be used."],
  },
  {
    dance: "quickstep",
    figureType: "telemark",
    name: "Telemark",
    timing: "SQQ",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "LF to side and slightly fwd (Closed Position.)",
    notes: ["NOTE - Timing: Alternative timing SSS may be used"],
  },
  {
    dance: "quickstep",
    figureType: "telemark-to-pp",
    name: "Telemark to PP",
    timing: "SQQ",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "LF to side (Promenade Position)",
    notes: ["NOTE - Timing: Alternative timing SSS may be used"],
  },
  { dance: "quickstep", figureType: "tipple-chasse-to-r", name: "Tipple Chassé to R" },
  {
    dance: "quickstep",
    figureType: "tipple-chasse-to-r-along-lod",
    name: "Tipple Chasse to R - Along LOD",
    timing: "SQQS",
    start: "LF bwd in CBMP (Outside Partner Position)",
    finish: "RF to side and slightly fwd (Closed Position)",
    notes: [
      "NOTE - General: Steps 2-4 only may be used",
      "NOTE - Foot Placement/Couple Position: Step 1 may be taken bwd in CBMP in Outside Partner",
    ],
  },
  {
    dance: "quickstep",
    figureType: "tipple-chasse-to-r-at-the-corner",
    name: "Tipple Chasse to R - at the Corner",
    timing: "SQQS",
    start: "LF bwd (Closed Position)",
    finish: "RF to side and slightly fwd (Closed Position)",
    notes: [
      "NOTE - Foot Placement/Couple Position: Step 1 may be taken bwd in CBMP in Outside Partner",
      "NOTE - General: Steps 2 - 4 only may be used",
    ],
  },
  {
    dance: "quickstep",
    figureType: "tipsy-to-l",
    name: "Tipsy to L",
    timing: "Q&Q",
    start: "LF to side, small step (Closed Position)",
    finish: "LF to side, small step (Closed Position)",
    notes: [],
  },
  {
    dance: "quickstep",
    figureType: "tipsy-to-r",
    name: "Tipsy to R",
    timing: "Q&Q",
    start: "RF to side, small step (Closed Position)",
    finish: "RF to side, small step (Closed Position)",
    notes: [],
  },
  { dance: "quickstep", figureType: "tipsy-to-r-or-l", name: "Tipsy to R or L" },
  {
    dance: "quickstep",
    figureType: "v6",
    name: "V6",
    timing: "SQQS SQQ",
    start: "LF bwd (Closed Position)",
    finish: "LF to side and slightly fwd (Closed Position)",
    notes: ["NOTE-General: it may start from step 2."],
  },
  {
    dance: "quickstep",
    figureType: "weave-from-pp",
    name: "Weave from PP",
    timing: "SQQ SQQ",
    start: "RF fwd and across in CBMP (Promenade Position)",
    finish: "LF to side and slightly fwd (Closed Position)",
    notes: [
      "NOTE - General: steps 1-3 or 4-6 only may be used.",
      "NOTE - Couple Position: may end in Promenade position",
    ],
  },
  {
    dance: "quickstep",
    figureType: "whisk",
    name: "Whisk",
    timing: "SSS",
    start: "LF fwd (Closed Position)",
    finish: "LF crossed behind (Promenade Position)",
    notes: ["NOTE - Timing: Alternative timing SQQ may be used"],
  },
  {
    dance: "quickstep",
    figureType: "wing",
    name: "Wing",
    timing: "S(QQ)",
    start: "RF fwd in CBMP (Outside Partner Position)",
    finish: "LF closes to RF w/o weight, weight on RF (Wing Position)",
    notes: [],
  },
  {
    dance: "quickstep",
    figureType: "wing-from-promenade-position",
    name: "Wing from Promenade Position",
    timing: "S(QQ)",
    start: "RF fwd and across in CBMP (Promenade Position)",
    finish: "LF closes to RF w/o weight, weight on RF (Wing Position)",
    notes: [],
  },
  {
    dance: "quickstep",
    figureType: "zig-zag",
    name: "Zig Zag",
    timing: "SS SQQS",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "RF diag bwd (Closed Position)",
    notes: ["NOTE - General: Steps 1-2 only may be used"],
  },
  {
    dance: "quickstep",
    figureType: "zig-zag-back-lock-and-running-finish",
    name: "Zig Zag, Back Lock and Running Finish",
  },
  {
    dance: "foxtrot",
    figureType: "back-feather",
    name: "Back Feather",
    timing: "SQQ",
    start: "LF bwd in CBMP (Outside Partner Position)",
    finish: "LF bwd in CBMP (Outside Partner Position)",
    notes: [],
  },
  {
    dance: "foxtrot",
    figureType: "back-whisk",
    name: "Back Whisk",
    timing: "SQQ",
    start: "LF bwd (Outside Partner Position)",
    finish: "LF crossed behind RF (Promenade Position)",
    notes: ["NOTE - Quantity of turn: It may turn up to 3/8 to R."],
  },
  {
    dance: "foxtrot",
    figureType: "basic-weave",
    name: "Basic Weave",
    timing: "QQQQQQ",
    start: "LF fwd (Closed Position)",
    finish: "RF fwd in CBMP (Outside Partner Position)",
    notes: ["NOTE - General: Steps 2-3 may be repeated (Extended Basic Weave)"],
  },
  {
    dance: "foxtrot",
    figureType: "bounce-fallaway-with-weave-ending",
    name: "Bounce Fallaway with Weave Ending",
    timing: "S&QQ QQQQ",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "RF fwd in CBMP (Outside Partner Position)",
    notes: ["NOTE - General: Figure may be extended by repeating steps 4-5."],
  },
  {
    dance: "foxtrot",
    figureType: "change-of-direction",
    name: "Change of Direction",
    timing: "SSS",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "LF fwd (Closed Position)",
    notes: ["NOTE - Quantity of turn: It may turn ½ to L when danced into a corner."],
  },
  {
    dance: "foxtrot",
    figureType: "closed-impetus-and-feather-finish",
    name: "Closed Impetus and Feather Finish",
  },
  { dance: "foxtrot", figureType: "closed-telemark", name: "Closed Telemark" },
  {
    dance: "foxtrot",
    figureType: "curved-feather",
    name: "Curved Feather",
    timing: "SQQ",
    start: "RF fwd (Closed Position)",
    finish: "RF fwd in CBMP (Outside Partner Position)",
    notes: [
      "NOTE - Foot Placement/Couple position: Step 1 may be taken fwd in CBMP in Outside Partner",
    ],
  },
  {
    dance: "foxtrot",
    figureType: "curved-feather-from-p-p",
    name: "Curved Feather from P.P.",
    timing: "SQQ",
    start: "RF fwd in CBMP (Promenade Position)",
    finish: "Weight on R foot (Outside Partner Position)",
    notes: [],
  },
  {
    dance: "foxtrot",
    figureType: "curved-feather-to-back-feather",
    name: "Curved Feather to Back Feather",
  },
  {
    dance: "foxtrot",
    figureType: "curved-three-step",
    name: "Curved Three Step",
    timing: "SQQ",
    start: "LF fwd (Closed Position)",
    finish: "LF fwd in CBMP (Closed Position)",
    notes: [],
  },
  {
    dance: "foxtrot",
    figureType: "double-reverse-spin",
    name: "Double Reverse Spin",
    timing: "SQ (Q) (SQ&Q Lady)",
    start: "LF FWD and slightly to side (Closed Position)",
    finish: "LF closes to RF w/o weight, weight on R foot (Closed Pos)",
    notes: ["NOTE - Timing: Alternative timing of SSQQ may be used."],
  },
  {
    dance: "foxtrot",
    figureType: "fallaway-reverse-and-slip-pivot",
    name: "Fallaway Reverse and Slip Pivot",
    timing: "QQQQ",
    start: "LF fwd in CBMP (Closed Position)",
    finish: "RF bwd (Slip Pivot) (Closed Position)",
    notes: [
      "NOTE - Timing: alternative timing S&QQ or SQQS may be used.",
      "NOTE - Quantity of turn: The figure may be danced without turn on step 4, when danced into a",
    ],
  },
  {
    dance: "foxtrot",
    figureType: "feather-ending",
    name: "Feather Ending",
    timing: "SQQ",
    start: "RF fwd in CBMP (Promenade Position)",
    finish: "RF fwd in CBMP (Outside Partner Position)",
    notes: [],
  },
  {
    dance: "foxtrot",
    figureType: "feather-finish",
    name: "Feather Finish",
    timing: "SQQ",
    start: "RF bwd and slightly to side (Closed Position)",
    finish: "RF fwd in CBMP (Outside Partner Position)",
    notes: [],
  },
  {
    dance: "foxtrot",
    figureType: "feather-step",
    name: "Feather Step",
    timing: "SQQ",
    start: "RF fwd (Closed Position)",
    finish: "RF fwd in CBMP (Outside Partner Position)",
    notes: [
      "NOTE - Foot Placement/Couple position: Step 1 may be taken fwd in CBMP in Outside Partner",
    ],
  },
  {
    dance: "foxtrot",
    figureType: "heel-pull-finish",
    name: "Heel Pull Finish",
    timing: "SSS",
    start: "LF bwd (Closed Position)",
    finish: "LF fwd (Closed Position)",
    notes: [
      "NOTE - General: Steps 1-2 only may be used (Timing QQS-Hesitation).",
      "NOTE - Timing: Alternative timing SSS or QQS may be used.",
    ],
  },
  {
    dance: "foxtrot",
    figureType: "hover-corte",
    name: "Hover Corte",
    timing: "SQQ",
    start: "RF bwd and slightly to side (Closed Position)",
    finish: "Transfer weight to RF (Closed Position)",
    notes: [
      "NOTE - Timing: alternative timing SSS may be used",
      "NOTE - Couple Position: it may start in Promenade Position",
      "NOTE - General: follow with Weave Ending (3-6 Basic Weave)",
    ],
  },
  {
    dance: "foxtrot",
    figureType: "hover-cross",
    name: "Hover Cross",
    timing: "SQQ QQQQ",
    start: "RF fwd and slightly to side (Closed Position)",
    finish: "RF fwd in CBMP (Outside Partner Position)",
    notes: [
      "NOTE - Foot Placement/Couple position: It may start from Promenade Position. Step 1 may be",
    ],
  },
  { dance: "foxtrot", figureType: "hover-feather", name: "Hover Feather" },
  {
    dance: "foxtrot",
    figureType: "hover-telemark",
    name: "Hover Telemark",
    timing: "SQQ",
    start: "LF diag fwd (Closed Position)",
    finish: "LF diag fwd (Closed Position)",
    notes: [],
  },
  {
    dance: "foxtrot",
    figureType: "hover-telemark-to-p-p",
    name: "Hover Telemark to P.P",
    timing: "SQQ",
    start: "LF diag fwd (Closed Position)",
    finish: "LF to side (Promenade Position)",
    notes: [],
  },
  {
    dance: "foxtrot",
    figureType: "impetus",
    name: "Impetus",
    timing: "SQQ",
    start: "LF bwd and slightly to side (Closed Position)",
    finish: "LF to side and slightly bwd (Closed Position)",
    notes: [],
  },
  {
    dance: "foxtrot",
    figureType: "impetus-to-p-p",
    name: "Impetus to P.P.",
    timing: "SQQ",
    start: "LF bwd and slightly to side (Closed Position)",
    finish: "LF diag fwd L side leading (Promenade Position)",
    notes: [],
  },
  {
    dance: "foxtrot",
    figureType: "natural-hover-telemark",
    name: "Natural Hover Telemark",
    timing: "SQQ SQQ",
    start: "RF fwd and slightly to side (Closed Position)",
    finish: "RF fwd in CBMP (Outside Partner Position)",
    notes: [
      "NOTE - Couple position: Step 1 may be danced fwd in CBMP in Outside Partner Position. It may start",
    ],
  },
  {
    dance: "foxtrot",
    figureType: "natural-telemark",
    name: "Natural Telemark",
    timing: "SQQQQ",
    start: "RF fwd and slightly to side (Closed Position)",
    finish: "RF fwd in CBMP (Outside Partner Position)",
    notes: [
      "NOTE - Couple position: Step 1 may be danced fwd in CBMP in Outside Partner Position.",
    ],
  },
  {
    dance: "foxtrot",
    figureType: "natural-turn",
    name: "Natural Turn",
    timing: "SQQ",
    start: "RF fwd and slightly to side (Closed Position)",
    finish: "RF bwd (Closed Position)",
    notes: [
      "NOTE - Foot Placement/Couple position: Step 1 may be danced in CBMP in Outside Partner Position.",
    ],
  },
  {
    dance: "foxtrot",
    figureType: "natural-twist-turn",
    name: "Natural Twist Turn",
    timing: "SQ&Q SQQ",
    start: "RF fwd (Closed Position)",
    finish: "RF in CBMP (Outside Partner Position)",
    notes: [
      "NOTE - Couple position: it may start in Prom Pos. Step 1 may be taken fwd in CBMP in Outside Partner",
    ],
  },
  {
    dance: "foxtrot",
    figureType: "natural-weave",
    name: "Natural Weave",
    timing: "SQQ QQQQ",
    start: "RF fwd and slightly to side (Closed Position)",
    finish: "RF fwd in CBMP (Outside Partner Position)",
    notes: [
      "NOTE - General: Steps 3-4 may be repeated (Extended Natural Weave).",
      "NOTE - Foot Placement/Couple position: It may start from Prom Pos. Step 1 may be danced in CBMP",
    ],
  },
  {
    dance: "foxtrot",
    figureType: "natural-zig-zag-from-p-p",
    name: "Natural Zig Zag from P.P.",
    timing: "SQQQQ",
    start: "RF fwd and across in CBMP (Promenade Position)",
    finish: "RF fwd in CBMP (Outside Partner Position)",
    notes: [],
  },
  { dance: "foxtrot", figureType: "natural-zig-zag-from-pp", name: "Natural Zig-Zag from PP" },
  { dance: "foxtrot", figureType: "open-impetus", name: "Open Impetus" },
  {
    dance: "foxtrot",
    figureType: "open-natural-turn",
    name: "Open Natural Turn",
    timing: "SQQ",
    start: "RF fwd and across in CBMP (Promenade Position)",
    finish: "RF bwd R side leading (Closed Position)",
    notes: ["NOTE - Couple position: Step 1 may be danced in CBMP in Outside Partner Position."],
  },
  {
    dance: "foxtrot",
    figureType: "open-telemark-and-feather-ending",
    name: "Open Telemark and Feather Ending",
  },
  {
    dance: "foxtrot",
    figureType: "open-telemark-natural-turn-outside-swivel-feather-ending",
    name: "Open Telemark, Natural Turn, Outside Swivel, Feather Ending",
  },
  {
    dance: "foxtrot",
    figureType: "outside-swivel",
    name: "Outside Swivel",
    timing: "S",
    start: "LF bwd in CBMP (Outside Partner Position)",
    finish: "Weight on LF (Promenade Position)",
    notes: [
      "NOTE - Timing: Additional S may be used.",
      "NOTE - Quantity of turn: Swivel may be turned up to 3/8 to R.",
    ],
  },
  {
    dance: "foxtrot",
    figureType: "quick-open-reverse-turn",
    name: "Quick Open Reverse Turn",
    timing: "SQ&QQQ",
    start: "RF fwd in CBMP (Outside Partner Position)",
    finish: "Weight on R foot (Outside Partner Position)",
    notes: [
      "NOTE - General: Steps 1-4 only may be used. The figure can start from step 2.",
      "NOTE - Couple position: The figure may start from Promenade Position.",
    ],
  },
  {
    dance: "foxtrot",
    figureType: "reverse-pivot",
    name: "Reverse Pivot",
    timing: "S",
    start: "RF diag BWD (Closed Position)",
    finish: "Weight on R F (Closed Position)",
    notes: [
      "NOTE - Timing: Alternative timing Q or & may be used. If Q is used the timing of the following figure",
    ],
  },
  {
    dance: "foxtrot",
    figureType: "reverse-turn",
    name: "Reverse Turn",
    timing: "SQQ",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "LF bwd (Closed Position)",
    notes: [],
  },
  {
    dance: "foxtrot",
    figureType: "reverse-turn",
    name: "Reverse Turn (incorporating Feather Finish)",
  },
  {
    dance: "foxtrot",
    figureType: "reverse-wave",
    name: "Reverse Wave",
    timing: "SQQ SQQ QSQ",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "LF fwd (Closed Position)",
    notes: [
      "NOTE - General: Steps 1-4, 1-6 or 4-6 only may be used.",
      "NOTE- Rise and Fall: when steps 1-4 are used as a preceding figure to Basic Weave there is no",
    ],
  },
  {
    dance: "foxtrot",
    figureType: "telemark",
    name: "Telemark",
    timing: "SQQ",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "LF to side and slightly fwd (Closed Position)",
    notes: [],
  },
  {
    dance: "foxtrot",
    figureType: "telemark-to-p-p",
    name: "Telemark to P.P.",
    timing: "SQQ",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "LF to side (Promenade Position)",
    notes: [],
  },
  {
    dance: "foxtrot",
    figureType: "three-step",
    name: "Three Step",
    timing: "SQQ",
    start: "LF fwd (Closed Position)",
    finish: "LF fwd (Closed Position)",
    notes: [],
  },
  {
    dance: "foxtrot",
    figureType: "top-spin",
    name: "Top Spin",
    timing: "QQQQ",
    start: "LF bwd in CBMP (Outside Partner Position)",
    finish: "RF fwd in CBMP (Outside Partner Position)",
    notes: [],
  },
  {
    dance: "foxtrot",
    figureType: "weave-from-p-p",
    name: "Weave from P.P.",
    timing: "SQQ QQQQ",
    start: "RF fwd and across in CBMP (Promenade Position)",
    finish: "RF fwd in CBMP (Outside Partner Position)",
    notes: [
      "NOTE - General: Steps 3-4 may be repeated (Extended Weave from PP)",
      "NOTE - Foot Placement/Couple position: Step 1 may be danced fwd in CBMP in Outside Partner",
    ],
  },
  { dance: "foxtrot", figureType: "weave-from-pp", name: "Weave from PP" },
  {
    dance: "foxtrot",
    figureType: "whisk",
    name: "Whisk",
    timing: "SQQ",
    start: "LF fwd (Closed Position)",
    finish: "LF crossed behind RF (Promenade Position)",
    notes: ["NOTE - Quantity of turn: It may turn up to ¼ to L."],
  },
  {
    dance: "tango",
    figureType: "back-corte",
    name: "Back Corté",
    timing: "SQQS",
    start: "LF to side (Closed Position)",
    finish: "RF closes to LF slightly bwd (Closed Position)",
    notes: [
      "NOTE - General: Open Finish may be used instead of the Closed Finish. Steps 2-4 only may be used.",
    ],
  },
  {
    dance: "tango",
    figureType: "back-open-promenade",
    name: "Back Open Promenade",
    timing: "SQQS",
    start: "LF to side (Promenade Position)",
    finish: "RF bwd in CBMP (Closed Position)",
    notes: [
      "NOTE - General/Timing: steps 3 and 4 may be repeated. Timing will be SS or &S.",
      "NOTE - General: it may start from step 2.",
    ],
  },
  {
    dance: "tango",
    figureType: "basic-reverse-turn",
    name: "Basic Reverse Turn",
    timing: "QQS QQS",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "RF closes to LF slightly bwd (Closed Position)",
    notes: [
      "NOTE - General: steps 1-3 or 4-6 only may be used. Closed Finish may be replaced with Open Finish.",
    ],
  },
  {
    dance: "tango",
    figureType: "brush-tap",
    name: "Brush Tap",
    timing: "QQ&S",
    start: "LF FWD and slightly to side (Closed Position)",
    finish: "LF placed to side w/o weight, weight on R foot (Closed Position)",
    notes: [
      "NOTE - Quantity of turn: more turn may be made between steps 1 and 2, up to ¼ to L. Figure may",
      "NOTE - Couple position: may end in Promenade Position.",
    ],
  },
  {
    dance: "tango",
    figureType: "chase",
    name: "Chase",
    timing: "SQQ QQS",
    start: "LF to side (Promenade Position)",
    finish: "RF to side and slightly fwd, LF placed to side w/o weight (Promenade Position)",
    notes: [
      "NOTE - General: it may start from step 2. It may finish in Closed Position, Lady will turn only 5/8 to R",
      "NOTE - Timing: alternative timing could be used: SQQQQS&.",
    ],
  },
  {
    dance: "tango",
    figureType: "chase-alternative-endings-method-4-progressive",
    name: "Chase Alternative Endings - Method 4: Progressive",
    timing: "QQ",
    start: "LF fwd in CBMP (Closed Position)",
    finish: "RF to side and slightly bwd (Promenade Position)",
    notes: [],
  },
  {
    dance: "tango",
    figureType: "closed-promenade",
    name: "Closed Promenade",
    timing: "SQQS",
    start: "LF to side (Promenade Position)",
    finish: "RF closes to LF slightly bwd (Closed Position)",
    notes: [
      "NOTE - General: May start from step 2.",
      "NOTE - Couple position: Man may turn square to Lady on step 3.",
    ],
  },
  { dance: "tango", figureType: "contra-check", name: "Contra Check" },
  {
    dance: "tango",
    figureType: "fallaway-four-step",
    name: "Fallaway Four Step",
    timing: "QQQQ",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "RF closes to LF slightly bwd (Promenade Position)",
    notes: [],
  },
  {
    dance: "tango",
    figureType: "fallaway-in-promenade",
    name: "Fallaway IN Promenade",
    timing: "SQQ SQQ",
    start: "LF to side (Promenade Position)",
    finish: "RF closes to LF slightly bwd (Promenade Position)",
    notes: ["NOTE - General: it may start from step 2."],
  },
  { dance: "tango", figureType: "fallaway-promenade", name: "Fallaway Promenade" },
  {
    dance: "tango",
    figureType: "fallaway-reverse-and-slip-pivot",
    name: "Fallaway Reverse and Slip Pivot",
    timing: "QQQQ",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "LF to side (Prom Position)",
    notes: [
      "NOTE - Quantity of Turn: when danced into a corner there will be no turn on step 4 (Pivot). The",
      "NOTE - Timing: alternative timings may be used: QQS&, S&QQ, SQ&Q, SQQ&, SQQS.",
    ],
  },
  {
    dance: "tango",
    figureType: "five-step",
    name: "Five Step",
    timing: "QQQQS",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "Weight on R foot (Prom Position)",
    notes: [
      "NOTE - Quantity of Turn: may be underturned when danced into a corner.",
      "NOTE - Timing: alternative timing QQS&S or S&QQS may be used.",
    ],
  },
  {
    dance: "tango",
    figureType: "four-step",
    name: "Four Step",
    timing: "QQQQ",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "RF closes to LF slightly bwd (Promenade Position)",
    notes: ["NOTE - General: after steps 1-2 Outside Swivel may be danced."],
  },
  {
    dance: "tango",
    figureType: "four-step-change",
    name: "Four Step Change",
    timing: "QQ&S",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "RF bwd small step (Closed Position)",
    notes: ["NOTE - Timing: alternative timing QQQQ may be used."],
  },
  { dance: "tango", figureType: "lf-and-rf-rocks", name: "LF and RF Rocks" },
  {
    dance: "tango",
    figureType: "mini-five-step",
    name: "Mini Five Step",
    timing: "QQQQS",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "Weight on R foot (Prom Position)",
    notes: [
      "NOTE - Quantity of Turn: figure can be danced also without turn starting DC and continuing with the",
      "NOTE - Timing: alternative timing QQS&S or S&QQS may be used.",
    ],
  },
  { dance: "tango", figureType: "natural-promenade-turn", name: "Natural Promenade Turn" },
  {
    dance: "tango",
    figureType: "natural-rock-turn",
    name: "Natural Rock Turn",
    timing: "SQQS QQS",
    start: "RF fwd (Closed Position)",
    finish: "RF closes to LF slightly bwd (Closed Position)",
    notes: [
      "NOTE - General: when a Rock Turn follows the Natural Turn from PP, step 4 of the Natural Promenade",
    ],
  },
  {
    dance: "tango",
    figureType: "natural-turn-from-pp",
    name: "Natural Turn from PP",
    timing: "SQQS",
    start: "LF to side (Promenade Position)",
    finish: "Weight on R foot LF placed to side w/o weight (Promenade Position)",
    notes: [
      "NOTE - General: it may start from step 2.",
      "NOTE - Timing: alternative timing may be used- SQQS&.",
    ],
  },
  {
    dance: "tango",
    figureType: "natural-twist-turn-from-pp",
    name: "Natural Twist Turn from PP",
    timing: "SQQ SQQ",
    start: "LF to side (Promenade Position)",
    finish: "Weight on R foot LF placed slightly to side w/o weight (Promenade Position)",
    notes: [
      "NOTE - General: it may start from step 2.",
      "NOTE - Timing: use of alternative timing QQS is possible after step 3.",
      "NOTE - Couple Position/Quantity of Turn: it may end in Close Position. In this case the Man will turn",
    ],
  },
  {
    dance: "tango",
    figureType: "open-promenade",
    name: "Open Promenade",
    timing: "SQQS",
    start: "LF to side (Promenade Positon)",
    finish: "RF fwd in CBMP (Outside Partner Position)",
    notes: ["NOTE - General: May start from step 2."],
  },
  {
    dance: "tango",
    figureType: "open-reverse-turn",
    name: "Open Reverse Turn",
    timing: "QQS QQS",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "RF closes to LF slightly bwd (Closed Position)",
    notes: [
      "NOTE - General: steps 1-3 or 4-6 only may be used. Closed Finish may be replaced with Open Finish.",
    ],
  },
  {
    dance: "tango",
    figureType: "open-reverse-turn-partner-in-line",
    name: "Open Reverse Turn, Partner in Line",
  },
  {
    dance: "tango",
    figureType: "open-reverse-turn-partner-outside",
    name: "Open Reverse Turn, Partner Outside",
  },
  {
    dance: "tango",
    figureType: "outside-swivel-method-1-after-open-finish-and",
    name: "Outside Swivel Method 1 - After Open Finish and",
    timing: "SQQ",
    start: "LF bwd in CBMP (Outside Partner Position)",
    finish: "LF to side small step w/o weight, weight on R foot (Closed Position)",
    notes: [
      "NOTE - General: step 3 may be replaced by a Closed or Open Finish. It may end in PP (same as",
    ],
  },
  {
    dance: "tango",
    figureType: "outside-swivel-method-2-turning-to-l",
    name: "Outside Swivel Method 2 - Turning to L",
    timing: "SQQ",
    start: "LF bwd in CBMP (Outside Partner Position)",
    finish: "Weight on R foot LF to side small step w/o weight, weight on R foot (Closed Position)",
    notes: [
      "NOTE - General: steps 3 may be replaced by a Closed or Open Finish. It may end in PP (same as",
    ],
  },
  {
    dance: "tango",
    figureType: "outside-swivel-method-3-reverse-outside-swivel",
    name: "Outside Swivel Method 3 - Reverse Outside Swivel",
    timing: "QQS QQ",
    start: "LF bwd and slightly to side (Closed Position)",
    finish: "LF to side small step w/o weight, weight on R foot (Closed Position)",
    notes: [
      "NOTE - General: steps 3 may be replaced by a Closed or Open Finish. It may end in PP (same as",
      "NOTE - Quantity of Turn: may be underturned when danced into a corner.",
    ],
  },
  { dance: "tango", figureType: "outside-swivels", name: "Outside Swivels" },
  { dance: "tango", figureType: "oversway", name: "Oversway" },
  {
    dance: "tango",
    figureType: "progressive-link",
    name: "Progressive Link",
    timing: "QQ",
    start: "LF fwd in CMBP (Closed Position)",
    finish: "RF to side and slightly bwd (Promenade Position)",
    notes: [],
  },
  {
    dance: "tango",
    figureType: "progressive-side-step",
    name: "Progressive Side Step",
    timing: "QQS",
    start: "LF fwd in CBMP (Closed Position)",
    finish: "LF fwd in CBMP (Closed Position)",
    notes: [
      "NOTE - General: steps 1-2 only may be used.",
      "NOTE - Quantity of turn: figure may be turned up to 3/8 to L.",
    ],
  },
  {
    dance: "tango",
    figureType: "progressive-side-step-reverse-turn",
    name: "Progressive Side Step Reverse Turn",
    timing: "QQSS QQS QQS",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "RF closes to LF slightly bwd (Closed Position)",
    notes: [
      "NOTE - General: steps 1-4 or 1-7 only may be used. Figure may be danced with an Open Finish.",
    ],
  },
  { dance: "tango", figureType: "promenade-link", name: "Promenade Link" },
  {
    dance: "tango",
    figureType: "promenade-link-turned-to-left",
    name: "Promenade Link Turned to Left",
    timing: "SQQ",
    start: "LF to side (Promenade Position)",
    finish: "LF to side w/o weight (Closed Position)",
    notes: [
      "NOTE - General: it may start from step 2.",
      "NOTE - Couple Position/Quantity of Turn: it may end in Promenade Position. In this case the Lady",
    ],
  },
  {
    dance: "tango",
    figureType: "promenade-link-turned-to-right",
    name: "Promenade Link Turned to Right",
    timing: "SQQ",
    start: "LF to side (Promenade Position)",
    finish: "LF to side w/o weight (Closed Position)",
    notes: ["NOTE - General: it may start from step 2."],
  },
  {
    dance: "tango",
    figureType: "quick-reverse-turn",
    name: "Quick Reverse Turn",
    timing: "QQ& QQS",
    start: "LF fwd and slightly to side (Closed Position)",
    finish: "RF closes to LF slightly bwd (Closed Position)",
    notes: [
      "NOTE - General: steps 1-3 or 4-6 only may be used. Closed Finish may be replaced by Open Finish.",
    ],
  },
  {
    dance: "tango",
    figureType: "reverse-pivot",
    name: "Reverse Pivot",
    timing: "&",
    start: "RF Diag bwd (Closed Position)",
    finish: "RF diag. bwd (Closed Position)",
    notes: ["NOTE - Timing: alternative timing of S or Q may be used"],
  },
  {
    dance: "tango",
    figureType: "rock-on-left-foot",
    name: "Rock on Left Foot",
    timing: "QQS",
    start: "LF bwd L side leading (Closed Position)",
    finish: "LF bwd L side leading (Closed Position)",
    notes: [
      "NOTE - General: figure may be danced with steps 1 and 3 in CBMP following any Open Finish. If",
      "NOTE - Quantity of turn: up to ¼ to R may be made.",
    ],
  },
  {
    dance: "tango",
    figureType: "rock-on-right-foot",
    name: "Rock on Right Foot",
    timing: "QQS",
    start: "RF bwd in CBMP, L shoulder leading (Closed Position)",
    finish: "RF bwd in CBMP, L shoulder leading (Closed Position)",
    notes: [],
  },
  { dance: "tango", figureType: "rock-turn", name: "Rock Turn" },
  {
    dance: "tango",
    figureType: "tango-walk",
    name: "Tango Walk",
    timing: "SS",
    start: "LF fwd (Closed Position)",
    finish: "RF fwd (Closed Position)",
    notes: ["NOTE - General: LF or RF walk only may be used."],
  },
  { dance: "tango", figureType: "the-chase", name: "The Chase" },
  { dance: "tango", figureType: "walk", name: "Walk" },
];
