// FROZEN ORACLE — the book-verified entry/exit alignments of every charted figure,
// captured from docs/seed/figure-charts.json BEFORE the 2026-07-10 alignment-derivation
// migration (repo HEAD 662663a) dropped the redundant (derivable) exitAlignments from
// the seed. Each exit here was transcribed from the published WDSF/ISTD chart, so this
// table is the permanent regression oracle for deriveAlignments (alignment.ts): a
// figure whose seed no longer stores an exit must still DERIVE exactly the exit the
// book printed. NOT generated by scripts/gen-*.mjs — do not regenerate; a change to a
// figure's turns/entry that breaks its row here is a data regression to fix, not a
// fixture to update (unless the source chart itself was re-verified).
import type { Alignment } from "../doc-types";

export interface AlignmentOracleRow {
  /** `${dance}:${figureType}` — the FIGURE_STEPS / GENERATED_FIGURE_ALIGNMENTS key. */
  key: string;
  /** The book's entry alignment (the figure's start_alignment), leader's perspective. */
  entry: Alignment;
  /** The book's exit alignment — what derivation must reproduce for unflagged figures. */
  exit: Alignment;
}

export const ALIGNMENT_ORACLE: readonly AlignmentOracleRow[] = [
  {
    key: "foxtrot:back-feather",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "backing",
      direction: "LOD",
    },
  },
  {
    key: "foxtrot:back-whisk",
    entry: {
      qualifier: "backing",
      direction: "DC_against",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:basic-weave",
    entry: {
      qualifier: "facing",
      direction: "DC_against",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:bounce-fallaway-with-weave-ending",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:change-of-direction",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "foxtrot:curved-feather",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW_against",
    },
  },
  {
    key: "foxtrot:curved-feather-from-p-p",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW_against",
    },
  },
  {
    key: "foxtrot:curved-three-step",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DC_against",
    },
  },
  {
    key: "foxtrot:double-reverse-spin",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:feather-ending",
    entry: {
      qualifier: "pointing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:feather-finish",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:feather-step",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "foxtrot:heel-pull-finish",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "foxtrot:hover-corte",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "backing",
      direction: "DC_against",
    },
  },
  {
    key: "foxtrot:hover-cross",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "foxtrot:hover-telemark",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "foxtrot:hover-telemark-to-p-p",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "foxtrot:impetus",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "backing",
      direction: "DC_against",
    },
  },
  {
    key: "foxtrot:impetus-to-p-p",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "pointing",
      direction: "DC",
    },
  },
  {
    key: "foxtrot:natural-hover-telemark",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "foxtrot:natural-telemark",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "foxtrot:natural-turn",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "backing",
      direction: "LOD",
    },
  },
  {
    key: "foxtrot:natural-twist-turn",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "foxtrot:natural-weave",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:natural-zig-zag-from-p-p",
    entry: {
      qualifier: "pointing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:open-natural-turn",
    entry: {
      qualifier: "pointing",
      direction: "wall",
    },
    exit: {
      qualifier: "backing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:outside-swivel",
    entry: {
      qualifier: "pointing",
      direction: "LOD",
    },
    exit: {
      qualifier: "pointing",
      direction: "LOD",
    },
  },
  {
    key: "foxtrot:quick-open-reverse-turn",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:reverse-pivot",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:reverse-turn",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "backing",
      direction: "LOD",
    },
  },
  {
    key: "foxtrot:reverse-wave",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "foxtrot:telemark",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:telemark-to-p-p",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:three-step",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:top-spin",
    entry: {
      qualifier: "backing",
      direction: "ALOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "foxtrot:weave-from-p-p",
    entry: {
      qualifier: "pointing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:whisk",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:back-whisk",
    entry: {
      qualifier: "backing",
      direction: "DC_against",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:backward-lock",
    entry: {
      qualifier: "backing",
      direction: "DW",
    },
    exit: {
      qualifier: "backing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:cross-chasse",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:cross-swivel",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "quickstep:double-reverse-spin",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:fisht-tail",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:forward-lock",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:four-quick-run",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:hover-corte",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "backing",
      direction: "DC_against",
    },
  },
  {
    key: "quickstep:impetus",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "backing",
      direction: "DC",
    },
  },
  {
    key: "quickstep:impetus-to-pp",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "pointing",
      direction: "DC",
    },
  },
  {
    key: "quickstep:natural-pivot",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "quickstep:natural-spin-turn",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "backing",
      direction: "DC",
    },
  },
  {
    key: "quickstep:natural-turn",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "backing",
      direction: "LOD",
    },
  },
  {
    key: "quickstep:open-reverse-turn-quick-open-reverse",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "backing",
      direction: "LOD",
    },
  },
  {
    key: "quickstep:progressive-chasse-to-l",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:progressive-chasse-to-r",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "backing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:quarter-turn-to-r",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "backing",
      direction: "DC",
    },
  },
  {
    key: "quickstep:reverse-turn",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "backing",
      direction: "LOD",
    },
  },
  {
    key: "quickstep:rumba-cross",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "backing",
      direction: "LOD",
    },
  },
  {
    key: "quickstep:running-cross-chasse",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:running-finish",
    entry: {
      qualifier: "backing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "quickstep:running-natural-turn",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "quickstep:running-spin-turn",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "backing",
      direction: "DC",
    },
  },
  {
    key: "quickstep:six-quick-run",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:telemark",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:telemark-to-pp",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:tipple-chasse-to-r-along-lod",
    entry: {
      qualifier: "backing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:tipple-chasse-to-r-at-the-corner",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:tipsy-to-l",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:tipsy-to-r",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:v6",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:weave-from-pp",
    entry: {
      qualifier: "pointing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:whisk",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:wing",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "quickstep:wing-from-promenade-position",
    entry: {
      qualifier: "pointing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "quickstep:zig-zag",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "backing",
      direction: "DW",
    },
  },
  {
    key: "tango:back-corte",
    entry: {
      qualifier: "backing",
      direction: "centre",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:back-open-promenade",
    entry: {
      qualifier: "pointing",
      direction: "DW",
    },
    exit: {
      qualifier: "backing",
      direction: "DC",
    },
  },
  {
    key: "tango:basic-reverse-turn",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:brush-tap",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "tango:chase",
    entry: {
      qualifier: "pointing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "tango:chase-alternative-endings-method-4-progressive",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:closed-promenade",
    entry: {
      qualifier: "pointing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:fallaway-four-step",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "tango:fallaway-in-promenade",
    entry: {
      qualifier: "pointing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "wall",
    },
  },
  {
    key: "tango:five-step",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:four-step",
    entry: {
      qualifier: "facing",
      direction: "DW_against",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:four-step-change",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "backing",
      direction: "DW_against",
    },
  },
  {
    key: "tango:mini-five-step",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:natural-rock-turn",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:natural-turn-from-pp",
    entry: {
      qualifier: "pointing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:natural-twist-turn-from-pp",
    entry: {
      qualifier: "pointing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:open-reverse-turn",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:outside-swivel-method-1-after-open-finish-and",
    entry: {
      qualifier: "pointing",
      direction: "wall",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:outside-swivel-method-2-turning-to-l",
    entry: {
      qualifier: "pointing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "tango:outside-swivel-method-3-reverse-outside-swivel",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:progressive-link",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:progressive-side-step",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "tango:progressive-side-step-reverse-turn",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:promenade-link-turned-to-left",
    entry: {
      qualifier: "pointing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:promenade-link-turned-to-right",
    entry: {
      qualifier: "pointing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "wall",
    },
  },
  {
    key: "tango:quick-reverse-turn",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:reverse-pivot",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "tango:rock-on-left-foot",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "backing",
      direction: "DC",
    },
  },
  {
    key: "tango:rock-on-right-foot",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "backing",
      direction: "DC",
    },
  },
  {
    key: "tango:tango-walk",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "viennese_waltz:lf-backward-change-step-natural-to-reverse",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "backing",
      direction: "DW",
    },
  },
  {
    key: "viennese_waltz:lf-forward-change-step-reverse-to-natural",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "viennese_waltz:natural-turn",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "viennese_waltz:reverse-turn",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "viennese_waltz:rf-backward-change-step-reverse-to-natural",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "backing",
      direction: "DC",
    },
  },
  {
    key: "viennese_waltz:rf-forward-change-step-natural-to-reverse",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "waltz:back-whisk",
    entry: {
      qualifier: "backing",
      direction: "DC_against",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "waltz:backward-lock",
    entry: {
      qualifier: "backing",
      direction: "DW",
    },
    exit: {
      qualifier: "backing",
      direction: "DW",
    },
  },
  {
    key: "waltz:basic-weave",
    entry: {
      qualifier: "backing",
      direction: "DW",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "waltz:chasse-from-pp",
    entry: {
      qualifier: "pointing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "waltz:cross-hesitation-from-pp",
    entry: {
      qualifier: "pointing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "waltz:double-reverse-spin",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "waltz:drag-hesitation",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "backing",
      direction: "DW",
    },
  },
  {
    key: "waltz:hesitation-change",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "waltz:hover-corte",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "backing",
      direction: "DC_against",
    },
  },
  {
    key: "waltz:impetus",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "backing",
      direction: "DC",
    },
  },
  {
    key: "waltz:impetus-to-pp",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "pointing",
      direction: "DC",
    },
  },
  {
    key: "waltz:natural-spin-turn",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "backing",
      direction: "DC",
    },
  },
  {
    key: "waltz:natural-turn",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "waltz:natural-turning-lock",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "pointing",
      direction: "LOD",
    },
  },
  {
    key: "waltz:outside-change",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "waltz:outside-spin",
    entry: {
      qualifier: "backing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "waltz:progressive-chasse-to-r",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "backing",
      direction: "DW",
    },
  },
  {
    key: "waltz:quick-open-reverse",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "backing",
      direction: "LOD",
    },
  },
  {
    key: "waltz:reverse-turn",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "waltz:reverse-turning-lock",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "waltz:running-cross-chasse",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "waltz:running-finish",
    entry: {
      qualifier: "backing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "waltz:running-spin-turn",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "backing",
      direction: "DC",
    },
  },
  {
    key: "waltz:telemark",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "waltz:telemark-to-pp",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "waltz:weave-from-pp",
    entry: {
      qualifier: "pointing",
      direction: "DC",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "waltz:whisk",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "waltz:wing",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "waltz:wing-from-pp",
    entry: {
      qualifier: "pointing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "waltz:open-natural-turn",
    entry: {
      qualifier: "pointing",
      direction: "wall",
    },
    exit: {
      qualifier: "backing",
      direction: "DW",
    },
  },
  {
    key: "waltz:fallaway-natural-turn",
    entry: {
      qualifier: "pointing",
      direction: "DW",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "waltz:running-weave-from-pp",
    entry: {
      qualifier: "pointing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "waltz:overturned-running-spin-turn",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "waltz:left-whisk",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:contra-check",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "viennese_waltz:chasse-change-step",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "backing",
      direction: "DW",
    },
  },
  {
    key: "viennese_waltz:continuous-spin",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "viennese_waltz:reverse-pivots",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "viennese_waltz:hesitation-change",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "viennese_waltz:drag-hesitation",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "backing",
      direction: "DW",
    },
  },
  {
    key: "viennese_waltz:natural-spin-turn",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "backing",
      direction: "DC",
    },
  },
  {
    key: "viennese_waltz:telemark",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "viennese_waltz:natural-spin-turn-reverse-pivot",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "viennese_waltz:checked-natural-turn",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "viennese_waltz:natural-back-check",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "viennese_waltz:checked-reverse-turn",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "viennese_waltz:reverse-back-check",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "viennese_waltz:contra-check",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "viennese_waltz:left-whisk",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "viennese_waltz:running-weave",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "backing",
      direction: "DC",
    },
  },
  {
    key: "viennese_waltz:natural-fleckerl",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "viennese_waltz:reverse-fleckerl",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "viennese_waltz:check-from-reverse-to-natural-fleckerl",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW_against",
    },
  },
  {
    key: "viennese_waltz:overturned-natural-spin-turn",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "viennese_waltz:throwaway-oversway",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "viennese_waltz:throwaway-oversway-taken-after-1-3-of-reverse-turn",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "viennese_waltz:hover-reverse-turn",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "viennese_waltz:running-feather",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "viennese_waltz:running-feather-opening-to-promenade-position",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "viennese_waltz:double-reverse-spin-overspin",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "viennese_waltz:reverse-impetus-into-right-lunge",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "viennese_waltz:rudolph-fallaway",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "viennese_waltz:ronde-twist-turn",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "viennese_waltz:double-leg-ronde",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "viennese_waltz:swivel-to-promenade-pivot",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "backing",
      direction: "DW",
    },
  },
  {
    key: "viennese_waltz:swivel-to-promenade-link",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "tango:tap-alternative-entries-to-pp",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:whisk",
    entry: {
      qualifier: "facing",
      direction: "DW_against",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:back-whisk",
    entry: {
      qualifier: "backing",
      direction: "DC_against",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:telemark-to-pp",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "tango:open-natural-turn",
    entry: {
      qualifier: "pointing",
      direction: "wall",
    },
    exit: {
      qualifier: "backing",
      direction: "DW",
    },
  },
  {
    key: "tango:natural-twist-turn",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "tango:chase-alternative-endings-chase-chasse-common-steps-1-8",
    entry: {
      qualifier: "pointing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "tango:chase-alternative-endings-method-1-whisk-fwd-step-to-pp",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "tango:chase-alternative-endings-method-2-whisk-promenade-link",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "tango:chase-alternative-endings-method-3-whisk-close-step-to-pp",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "tango:oversway",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "wall",
    },
  },
  {
    key: "tango:drop-oversway",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "wall",
    },
  },
  {
    key: "tango:oversway-alternative-endings-method-1-transfer-weight-to-pp",
    entry: {
      qualifier: "facing",
      direction: "wall",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:oversway-alternative-endings-method-2-close-step-to-pp",
    entry: {
      qualifier: "facing",
      direction: "wall",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:oversway-alternative-endings-method-3-chasse-whisk-fwd-step-to-pp",
    entry: {
      qualifier: "facing",
      direction: "wall",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:oversway-alternative-endings-method-4-chasse-whisk-promenade-link",
    entry: {
      qualifier: "facing",
      direction: "wall",
    },
    exit: {
      qualifier: "facing",
      direction: "wall",
    },
  },
  {
    key: "tango:oversway-alternative-endings-method-5-chasse-whisk-close-step-to-pp",
    entry: {
      qualifier: "facing",
      direction: "wall",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "tango:oversway-alternative-endings-method-6-natural-spin-to-pp",
    entry: {
      qualifier: "facing",
      direction: "ALOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:hover-feather",
    entry: {
      qualifier: "facing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "foxtrot:outside-spin",
    entry: {
      qualifier: "backing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:natural-twist-turn-with-impetus-and-feather-finish",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "foxtrot:natural-twist-turn-with-impetus-to-p-p",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "pointing",
      direction: "centre",
    },
  },
  {
    key: "quickstep:basic-movement-quarter-turn-and-progressive-chasse",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:heel-pivot",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:outside-change",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:open-natural-turn",
    entry: {
      qualifier: "pointing",
      direction: "wall",
    },
    exit: {
      qualifier: "backing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:hesitation-change",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "facing",
      direction: "DC",
    },
  },
  {
    key: "quickstep:tipple-chasse-to-left",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "backing",
      direction: "LOD",
    },
  },
  {
    key: "quickstep:outside-spin",
    entry: {
      qualifier: "backing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:natural-turning-lock",
    entry: {
      qualifier: "backing",
      direction: "LOD",
    },
    exit: {
      qualifier: "pointing",
      direction: "LOD",
    },
  },
  {
    key: "quickstep:drag-hesitation",
    entry: {
      qualifier: "facing",
      direction: "LOD",
    },
    exit: {
      qualifier: "backing",
      direction: "DW",
    },
  },
  {
    key: "waltz:throwaway-oversway",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:throwaway-oversway",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:throwaway-oversway",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "tango:throwaway-oversway",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "waltz:oversway",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:oversway",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:oversway",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "facing",
      direction: "DW",
    },
  },
  {
    key: "waltz:hinge",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "foxtrot:hinge",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "quickstep:hinge",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "tango:hinge",
    entry: {
      qualifier: "backing",
      direction: "DC",
    },
    exit: {
      qualifier: "pointing",
      direction: "DW",
    },
  },
  {
    key: "waltz:same-foot-lunge",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "foxtrot:same-foot-lunge",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "quickstep:same-foot-lunge",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
  {
    key: "tango:same-foot-lunge",
    entry: {
      qualifier: "facing",
      direction: "DW",
    },
    exit: {
      qualifier: "facing",
      direction: "LOD",
    },
  },
];
